/* Banco de questões — Ciências (8º/9º ano) — protótipo GTA: Grande Trilha do Aprendizado */
window.QUESTOES = window.QUESTOES || {};
Object.assign(window.QUESTOES, {
  "cie-0": { q: [
    { t:"fix", q:"A energia que um corpo possui por estar em movimento, como a de um carro em alta velocidade, é chamada de energia:", opts:["potencial gravitacional","cinética","química","térmica"], a:1, exp:"Energia cinética é a energia do movimento: quanto maior a velocidade (e a massa) do corpo, maior ela é." },
    { t:"fix", q:"A energia do Sol chega à Terra atravessando o espaço vazio, na forma de:", opts:["calor por condução","energia química","corrente elétrica","energia radiante (luminosa)"], a:3, exp:"A luz solar é energia radiante, que se propaga por ondas eletromagnéticas e não precisa de meio material para viajar." },
    { t:"apl", q:"Numa usina hidrelétrica, a água represada desce por tubos, gira as turbinas e gera eletricidade. A sequência correta de transformações de energia nesse processo é:", opts:["potencial gravitacional → cinética → elétrica","cinética → térmica → elétrica","elétrica → cinética → potencial","química → potencial → cinética"], a:0, exp:"A água parada no alto tem energia potencial; ao descer, ganha movimento (cinética); as turbinas transformam esse movimento em energia elétrica." },
    { t:"apl", q:"Ao pedalar ladeira abaixo e frear de repente, Lucas percebeu que os freios da bicicleta esquentaram. Isso acontece porque o atrito dos freios transformou energia:", opts:["térmica em cinética","elétrica em térmica","cinética em térmica","potencial em química"], a:2, exp:"O movimento da bicicleta (energia cinética) é convertido em calor (energia térmica) pelo atrito entre as pastilhas e a roda, reduzindo a velocidade." },
    { t:"des", q:"Numa montanha-russa, o carrinho parte do ponto mais alto com certa energia potencial, desce ganhando velocidade e sobe a ladeira seguinte. Observa-se que ele nunca alcança a mesma altura de onde partiu. A explicação correta é:", opts:["a energia do carrinho foi destruída durante o percurso","parte da energia mecânica se transformou em calor pelo atrito com os trilhos e com o ar, mas a energia total se conservou","o carrinho perdeu massa durante o trajeto e por isso não sobe tanto","a gravidade aumentou na segunda subida, segurando o carrinho"], a:1, exp:"Energia não se perde nem se destrói: transforma-se. O atrito converte parte da energia mecânica em energia térmica, então sobra menos energia potencial na subida seguinte." }
  ] },
  "cie-1": { q: [
    { t:"fix", q:"Calor é definido corretamente como:", opts:["a medida da agitação das partículas de um corpo","uma substância quente que fica dentro dos objetos","energia térmica em trânsito, que passa espontaneamente do corpo mais quente para o mais frio","a mesma coisa que temperatura, medida em graus Celsius"], a:2, exp:"Calor é energia em transferência entre corpos de temperaturas diferentes; temperatura é a medida do estado de agitação das partículas. Os conceitos não se confundem." },
    { t:"fix", q:"O calor do Sol atravessa o espaço vazio até chegar à Terra. O processo de propagação de calor que não precisa de meio material é a:", opts:["irradiação","condução","convecção","evaporação"], a:0, exp:"Na irradiação, o calor se propaga por ondas eletromagnéticas, que viajam inclusive no vácuo. Condução e convecção precisam de meio material." },
    { t:"apl", q:"Ana deixou uma colher de metal dentro da panela de brigadeiro no fogo. Minutos depois, a ponta da colher, fora da panela, estava quente. O calor chegou até a ponta principalmente por:", opts:["convecção","irradiação","evaporação","condução"], a:3, exp:"Na condução, o calor se transmite de partícula a partícula através do material, sem que ele se desloque — processo típico dos sólidos, principalmente dos metais." },
    { t:"apl", q:"Os aparelhos de ar-condicionado costumam ser instalados na parte alta das paredes, e os aquecedores, perto do chão. A explicação física para isso é:", opts:["o ar quente desce e o ar frio sobe, formando correntes de convecção","o ar frio, mais denso, desce, e o ar quente sobe; a posição dos aparelhos aproveita a convecção para climatizar o ambiente","apenas uma questão de estética e de economia de fios","a irradiação funciona melhor na vertical do que na horizontal"], a:1, exp:"O ar frio, mais denso, desce; o quente, menos denso, sobe. Instalar os aparelhos nessas posições aproveita as correntes de convecção e espalha a temperatura pelo ambiente inteiro." },
    { t:"des", q:"Num dia frio, ao tocar a maçaneta de metal e a porta de madeira da mesma sala, sentimos o metal mais frio que a madeira, embora ambos estejam à mesma temperatura (a do ambiente). Isso ocorre porque:", opts:["o metal está sempre abaixo da temperatura ambiente","a madeira produz calor e o metal não","o metal é bom condutor e retira calor da mão mais rapidamente, causando a sensação de frio","a maçaneta recebe irradiação do ambiente e a porta, não"], a:2, exp:"Em equilíbrio térmico, tudo está à mesma temperatura. A diferença está no fluxo de calor: o metal conduz rápido o calor da mão, e o cérebro interpreta essa perda rápida como 'mais frio'." }
  ] },
  "cie-2": { q: [
    { t:"fix", q:"Na etiqueta de um chuveiro elétrico aparece a inscrição '220 V'. A grandeza indicada, medida em volts, é a:", opts:["tensão elétrica (diferença de potencial)","corrente elétrica","resistência elétrica","potência elétrica"], a:0, exp:"Volt (V) é a unidade de tensão elétrica. Corrente se mede em ampère (A), resistência em ohm (Ω) e potência em watt (W)." },
    { t:"fix", q:"Na instalação elétrica de uma casa, as tomadas e as lâmpadas são ligadas em paralelo, e não em série, principalmente porque:", opts:["em paralelo os fios gastam menos cobre","em série a conta de luz sai mais cara","em paralelo cada aparelho recebe a mesma tensão e funciona de forma independente dos demais","em série as lâmpadas queimam por excesso de tensão"], a:2, exp:"No circuito em paralelo, cada aparelho fica sob a mesma tensão da rede e pode ser ligado ou desligado sem afetar os outros; se um queimar, os demais continuam funcionando." },
    { t:"apl", q:"A resistência elétrica de um chuveiro é de 20 Ω e ele é ligado a uma rede de 220 V. Pela lei de Ohm (U = R × i), a corrente que atravessa o chuveiro é de:", opts:["4.400 A","11 A","0,09 A","240 A"], a:1, exp:"i = U ÷ R = 220 ÷ 20 = 11 A. O valor 4.400 A sai do erro de multiplicar em vez de dividir; 0,09 A vem de inverter a fórmula." },
    { t:"apl", q:"Duas lâmpadas foram ligadas corretamente na mesma rede de 110 V: uma de 60 W e outra de 100 W. Sobre o brilho e o consumo, é correto afirmar que a lâmpada de 100 W:", opts:["brilha menos, pois tem resistência maior","brilha igual, pois a tensão é a mesma","consome menos energia, pois é mais econômica","brilha mais e consome mais energia, pois transforma mais energia elétrica por segundo"], a:3, exp:"Potência é a rapidez com que o aparelho transforma energia elétrica. Na mesma tensão, a lâmpada de maior potência consome mais corrente, brilha mais e gasta mais energia." },
    { t:"des", q:"Um ferro de passar tem potência de 1.000 W e fica ligado 2 horas por dia, todos os dias de um mês de 30 dias. Se a energia custa R$ 0,80 por kWh, o gasto mensal só com o ferro é de:", opts:["R$ 16,00","R$ 60,00","R$ 48,00","R$ 1.600,00"], a:2, exp:"E = P × tempo: 1.000 W = 1 kW; 2 h × 30 dias = 60 h; E = 1 × 60 = 60 kWh. Custo: 60 × 0,80 = R$ 48,00." }
  ] },
  "cie-3": { q: [
    { t:"fix", q:"Numa lâmpada incandescente acesa, a principal transformação de energia é:", opts:["energia química em luminosa","energia luminosa em elétrica","energia térmica em cinética","energia elétrica em luminosa e térmica"], a:3, exp:"A corrente elétrica aquece o filamento até ele brilhar: a energia elétrica se transforma em luz e em muito calor — por isso essas lâmpadas desperdiçam tanta energia." },
    { t:"apl", q:"Um copo com gelo foi esquecido sobre a mesa da cozinha e, depois de um tempo, o gelo derreteu. A explicação fisicamente correta é:", opts:["o gelo cedeu frio para o ambiente até acabar","o gelo recebeu calor do ambiente, que está a temperatura maior, até mudar de estado físico","o copo produziu calor para aquecer o gelo","o gelo evaporou diretamente, sem passar pelo estado líquido"], a:1, exp:"O calor flui espontaneamente do corpo mais quente para o mais frio: o ambiente cedeu calor ao gelo, que fundiu. 'Frio' não é uma energia que se transfere." },
    { t:"apl", q:"Um aquecedor de 1.100 W foi ligado corretamente em uma tomada de 220 V. A corrente elétrica que passa pelo aparelho, dada por i = P ÷ U, é de:", opts:["5 A","0,2 A","20 A","242.000 A"], a:0, exp:"i = 1.100 ÷ 220 = 5 A. Multiplicar P por U (242.000 A) ou inverter a divisão (0,2 A) são erros comuns de aplicação da fórmula." },
    { t:"des", q:"Uma família trocou as 10 lâmpadas incandescentes de 60 W por lâmpadas de LED de 10 W, com a mesma luminosidade, usadas 5 horas por dia. Em 30 dias, a economia de energia foi de:", opts:["7,5 kWh","15 kWh","75 kWh","150 kWh"], a:2, exp:"Economia por lâmpada: 60 − 10 = 50 W. Total: 10 × 50 = 500 W = 0,5 kW. Tempo: 5 × 30 = 150 h. Economia: 0,5 × 150 = 75 kWh." },
    { t:"des", q:"Num experimento, 200 g de água a 20 °C foram aquecidos até 60 °C. Sabendo que o calor específico da água é 1 cal/g°C, a quantidade de calor absorvida pela água (Q = m × c × ΔT) foi de:", opts:["8.000 cal","4.000 cal","80 cal","12.000 cal"], a:0, exp:"Q = 200 × 1 × (60 − 20) = 200 × 40 = 8.000 cal. Esquecer a variação de temperatura e usar 60 no lugar de 40 levaria ao erro de 12.000 cal." }
  ] },
  "cie-4": { q: [
    { t:"fix", q:"Na tabela periódica atual, os elementos químicos estão organizados principalmente em ordem crescente de:", opts:["massa atômica","tamanho do átomo","número atômico (quantidade de prótons)","data de descoberta"], a:2, exp:"A tabela moderna ordena os elementos pelo número atômico Z, que é a quantidade de prótons no núcleo. Elementos da mesma coluna têm propriedades semelhantes." },
    { t:"fix", q:"No modelo atômico atual, a distribuição das partículas do átomo é:", opts:["prótons e nêutrons no núcleo; elétrons ao redor, na eletrosfera","elétrons e nêutrons no núcleo; prótons na eletrosfera","prótons, nêutrons e elétrons misturados numa esfera maciça","elétrons no núcleo; prótons e nêutrons na eletrosfera"], a:0, exp:"O núcleo, pequeno e denso, concentra prótons e nêutrons; os elétrons, de carga negativa, ocupam a eletrosfera ao redor do núcleo." },
    { t:"apl", q:"Um átomo de sódio tem número atômico 11 e número de massa 23. Como o número de massa é a soma de prótons e nêutrons, a quantidade de nêutrons desse átomo é:", opts:["11","23","34","12"], a:3, exp:"Nêutrons = A − Z = 23 − 11 = 12. Somar 23 + 11 = 34 é o erro típico de quem inverte a relação entre as grandezas." },
    { t:"apl", q:"O lítio, o sódio e o potássio estão na mesma coluna da tabela periódica (grupo 1) e apresentam reações químicas parecidas — todos reagem violentamente com água, por exemplo. Essa semelhança se explica porque eles têm:", opts:["o mesmo número de nêutrons","o mesmo número de elétrons na última camada (camada de valência)","a mesma massa atômica","o mesmo número de camadas eletrônicas"], a:1, exp:"O que define o comportamento químico é a camada de valência. Os metais alcalinos têm 1 elétron na última camada e por isso reagem de modo semelhante." },
    { t:"des", q:"O magnésio tem número atômico 12 e tende a perder 2 elétrons, formando o íon Mg²⁺. Sobre esse íon, é correto dizer que ele tem:", opts:["12 prótons e 12 elétrons","10 prótons e 12 elétrons","12 prótons e 10 elétrons","14 prótons e 12 elétrons"], a:2, exp:"O número de prótons não muda: 12. Ao perder 2 elétrons, o íon fica com 10 elétrons e com 2 cargas positivas a mais — daí a carga 2+." }
  ] },
  "cie-5": { q: [
    { t:"fix", q:"No cloreto de sódio (NaCl), o sal de cozinha, o sódio transfere um elétron para o cloro, e os íons formados se atraem. Esse tipo de ligação química é a:", opts:["ligação iônica","ligação covalente","ligação metálica","ligação de hidrogênio"], a:0, exp:"A ligação iônica ocorre com transferência de elétrons, em geral entre metal e ametal, formando íons de cargas opostas que se atraem." },
    { t:"fix", q:"Na molécula de água (H₂O), os átomos de hidrogênio e oxigênio estão unidos por:", opts:["transferência de elétrons, formando íons","uma grade de íons positivos e negativos","elétrons livres que circulam entre os átomos","compartilhamento de pares de elétrons (ligação covalente)"], a:3, exp:"Na ligação covalente, típica entre ametais, os átomos compartilham pares de elétrons para completar suas camadas de valência." },
    { t:"apl", q:"A fórmula do ácido sulfúrico é H₂SO₄. O número total de átomos em uma molécula dessa substância é:", opts:["3","6","7","4"], a:2, exp:"H₂ indica 2 hidrogênios; S, 1 enxofre; O₄, 4 oxigênios. Total: 2 + 1 + 4 = 7 átomos. Contar só os elementos (3) é o erro mais comum." },
    { t:"apl", q:"O sal de cozinha sólido não conduz corrente elétrica, mas, dissolvido em água, conduz muito bem. Isso acontece porque, em solução:", opts:["o sal vira metal e passa a ter elétrons livres","os íons Na⁺ e Cl⁻ se separam e ficam livres para se movimentar, transportando cargas","a água pura passa a conduzir eletricidade","as moléculas de sal absorvem a corrente"], a:1, exp:"Compostos iônicos, ao se dissolver, liberam íons móveis que conduzem corrente. No sólido, os íons estão presos na estrutura cristalina; a água pura praticamente não conduz." },
    { t:"des", q:"O cálcio (grupo 2) forma o íon Ca²⁺, e o cloro (grupo 17) forma o íon Cl⁻. Para que o composto formado entre eles seja eletricamente neutro, sua fórmula deve ser:", opts:["CaCl₂","CaCl","Ca₂Cl","CaCl₃"], a:0, exp:"Cada Ca²⁺ tem 2 cargas positivas; são necessários 2 Cl⁻ para equilibrar: (+2) + 2×(−1) = 0. Por isso a fórmula é CaCl₂." }
  ] },
  "cie-6": { q: [
    { t:"fix", q:"Qual dos fenômenos abaixo é uma reação química, pois há formação de novas substâncias?", opts:["o derretimento do gelo num copo de suco","a dissolução de açúcar no café","a evaporação da água de uma poça","o enferrujamento de um portão de ferro"], a:3, exp:"Na ferrugem, o ferro reage com o oxigênio e a umidade formando uma substância nova, o óxido de ferro. Derreter, dissolver e evaporar são fenômenos físicos: a substância não muda." },
    { t:"fix", q:"Segundo a Lei de Lavoisier (lei da conservação das massas), em uma reação química realizada em sistema fechado:", opts:["a massa dos produtos é sempre maior que a dos reagentes","a massa total dos reagentes é igual à massa total dos produtos","a massa diminui, pois parte da matéria vira energia e desaparece","a massa varia conforme a temperatura da reação"], a:1, exp:"Num sistema fechado, os átomos se rearranjam, mas nenhum se perde: a massa total se conserva. Se gases escapam (sistema aberto), a balança marca menos — mas a lei continua valendo." },
    { t:"apl", q:"Ao queimar uma vela de parafina, observa-se liberação de calor, luz e formação de gás carbônico e vapor de água. A queima da vela é um fenômeno:", opts:["físico, pois a vela apenas muda de forma","físico, pois a parafina derrete antes de queimar","químico, pois reagentes (parafina e oxigênio) originam novas substâncias, com liberação de energia","químico apenas enquanto o pavio está aceso"], a:2, exp:"A combustão é reação química: a parafina reage com o oxigênio do ar e forma CO₂ e água, liberando energia. O derretimento da parafina, esse sim, é físico." },
    { t:"apl", q:"Na reação de formação da amônia, N₂ + 3 H₂ → 2 NH₃, quantas moléculas de amônia se formam quando 3 moléculas de hidrogênio reagem completamente?", opts:["2","3","1","6"], a:0, exp:"A equação já está balanceada e mostra a proporção: 3 moléculas de H₂ produzem 2 de NH₃. Os coeficientes indicam a proporção entre as moléculas." },
    { t:"des", q:"Uma aluna colocou um comprimido efervescente inteiro em um copo de água fria e outro comprimido triturado (em pó) em um copo igual de água quente. No segundo copo, a efervescência foi muito mais rápida. As duas condições que aceleraram a reação foram:", opts:["o pó, que é mais leve, e a água, que ferve mais rápido","a pressão dentro do copo e a cor da água","apenas a temperatura, pois a trituração não interfere","a maior superfície de contato do comprimido triturado e a maior temperatura da água"], a:3, exp:"Triturar aumenta a superfície de contato entre os reagentes, e a temperatura maior aumenta a energia das partículas e a frequência dos choques entre elas. Os dois fatores aceleram a reação." }
  ] },
  "cie-7": { q: [
    { t:"fix", q:"O gás oxigênio (O₂) é uma substância simples e a água (H₂O) é uma substância composta, porque:", opts:["a água é líquida e o oxigênio é gasoso","o O₂ é formado por átomos de um único elemento, e a H₂O, por átomos de elementos diferentes","o O₂ tem menos átomos que a H₂O","a água conduz eletricidade e o oxigênio não"], a:1, exp:"Substância simples tem átomos de um só elemento químico (O₂, N₂, Fe); composta reúne dois ou mais elementos combinados (H₂O, CO₂, NaCl)." },
    { t:"apl", q:"O cloro tem número atômico 17. Para ficar estável, seus átomos tendem a ganhar 1 elétron. O íon formado e sua carga são:", opts:["Cl⁺, pois ganhou uma carga positiva","Cl¹⁷, pois o número atômico aumentou","Cl²⁻, pois ganhou 2 elétrons","Cl⁻, pois ficou com um elétron a mais que prótons"], a:3, exp:"Ao ganhar 1 elétron (carga negativa), o átomo fica com 17 prótons e 18 elétrons: o saldo é uma carga negativa, formando o ânion Cl⁻." },
    { t:"apl", q:"A glicose, açúcar usado pelas células na respiração, tem fórmula C₆H₁₂O₆. Uma molécula de glicose é formada por quantos átomos no total?", opts:["3","12","24","18"], a:2, exp:"Somam-se os índices da fórmula: 6 carbonos + 12 hidrogênios + 6 oxigênios = 24 átomos." },
    { t:"des", q:"O alumínio (Z = 13) perde 3 elétrons formando o íon Al³⁺, e o oxigênio ganha 2 elétrons formando O²⁻. A fórmula do óxido de alumínio, composto neutro formado por esses íons, é:", opts:["Al₂O₃","AlO","Al₃O₂","AlO₂"], a:0, exp:"Para zerar as cargas: 2 íons Al³⁺ dão +6 e 3 íons O²⁻ dão −6. Logo, a fórmula é Al₂O₃ — as cargas de um íon viram os índices do outro." },
    { t:"des", q:"Considere a reação balanceada 2 H₂ + O₂ → 2 H₂O. Se 4 moléculas de hidrogênio reagirem com oxigênio em quantidade suficiente, o número de moléculas de água formadas será:", opts:["2","8","4","6"], a:2, exp:"A proporção da equação é 2 H₂ → 2 H₂O, ou seja, 1 para 1. Dobrando o hidrogênio (4 moléculas), dobra a água: 4 moléculas." }
  ] },
  "cie-8": { q: [
    { t:"fix", q:"A organela responsável pela respiração celular — processo que libera energia (ATP) a partir da glicose — é a:", opts:["mitocôndria","cloroplasto","lisossomo","vacúolo"], a:0, exp:"A mitocôndria é a 'usina' da célula: na respiração celular, transforma a energia da glicose em ATP, usado em todas as atividades celulares." },
    { t:"fix", q:"As bactérias são organismos procariontes. Isso significa que suas células:", opts:["têm núcleo envolvido por membrana","possuem muitas mitocôndrias","não têm núcleo definido: o material genético fica solto no citoplasma","são sempre maiores que as células animais"], a:2, exp:"Células procariontes não têm carioteca (membrana nuclear): o DNA fica disperso no citoplasma. As eucariontes, como as nossas, têm núcleo organizado." },
    { t:"apl", q:"Ao microscópio, uma estudante observou uma célula com parede celular rígida e cloroplastos esverdeados. Ela pode concluir que se trata de uma célula:", opts:["animal, pois tem membrana","vegetal, pois parede celular e cloroplastos não existem em células animais","de bactéria, pois é esverdeada","de fungo, pois tem parede celular"], a:1, exp:"Parede celular e cloroplastos (onde ocorre a fotossíntese) são características das células vegetais e das algas. Células animais têm apenas membrana, sem parede." },
    { t:"apl", q:"As células do pâncreas produzem grande quantidade de enzimas, que são proteínas. Por isso, essas células apresentam grande quantidade de:", opts:["cloroplastos, para produzir açúcar","vacúolos, para armazenar as enzimas","paredes celulares, para proteger a produção","ribossomos, as organelas que fabricam proteínas"], a:3, exp:"Ribossomos são as 'fábricas' de proteínas da célula. Células especializadas em produzir proteínas têm muitos ribossomos e retículo endoplasmático rugoso desenvolvido." },
    { t:"des", q:"Certa toxina destrói especificamente o complexo golgiense, organela que empacota e exporta as substâncias produzidas pela célula. O tecido do corpo humano que seria afetado mais rapidamente é o:", opts:["das glândulas salivares, que secretam enzimas para fora da célula","dos ossos, que dependem de fotossíntese","da pele, que serve apenas de barreira contra a toxina","dos músculos, que não produzem substância alguma"], a:0, exp:"O raciocínio tem duas etapas: o complexo golgiense empacota e secreta substâncias; logo, os tecidos mais secretores — como as glândulas salivares — sentem primeiro a falta dele." }
  ] },
  "cie-9": { q: [
    { t:"fix", q:"Os genes, responsáveis por determinar características como a cor dos olhos, são:", opts:["proteínas produzidas pelas mitocôndrias","células do sangue que carregam informações","segmentos de DNA localizados nos cromossomos","organelas encontradas no citoplasma"], a:2, exp:"Um gene é um trecho da molécula de DNA que guarda a receita de uma característica. Os genes ficam organizados nos cromossomos, dentro do núcleo." },
    { t:"fix", q:"O genótipo de um organismo é:", opts:["o aspecto visível de suas características","sua constituição genética, ou seja, o conjunto de genes que ele herdou","o ambiente em que ele vive","a quantidade de cromossomos de suas células"], a:1, exp:"Genótipo é o conjunto de genes herdados; fenótipo é a característica que se expressa, resultado do genótipo somado às influências do ambiente." },
    { t:"apl", q:"Nas ervilhas, o alelo para flor roxa (P) é dominante sobre o de flor branca (p). Cruzando uma planta Pp com uma planta pp, a proporção esperada de descendentes com flores brancas (pp) é de:", opts:["100%","75%","25%","50%"], a:3, exp:"Os cruzamentos possíveis são Pp, Pp, pp e pp: metade (50%) recebe p dos dois pais e terá flores brancas; a outra metade (Pp) terá flores roxas." },
    { t:"apl", q:"Pessoas com sangue tipo O são chamadas de doadoras universais no sistema ABO porque:", opts:["não têm os antígenos A nem B nas hemácias, então seu sangue não provoca reação de defesa nos receptores","têm os dois antígenos, A e B, e por isso combinam com qualquer sangue","produzem anticorpos contra todos os tipos sanguíneos","têm o tipo de sangue mais comum no Brasil"], a:0, exp:"As hemácias do tipo O não apresentam antígenos A nem B na superfície; por isso o sistema de defesa do receptor não as reconhece como estranhas. Quem tem sangue AB é o receptor universal." },
    { t:"des", q:"A cor de olhos castanha (B) é dominante sobre a azul (b). Um casal de olhos castanhos teve um filho de olhos azuis (bb). Sobre os genótipos dos pais, conclui-se que:", opts:["ambos são BB, pois têm olhos castanhos","um é BB e o outro é bb","ambos são Bb, pois o filho bb herdou um alelo b de cada um","é impossível que pais de olhos castanhos tenham filho de olhos azuis"], a:2, exp:"Para ser bb, o filho precisou receber um b do pai e um b da mãe. Como os dois têm olhos castanhos, cada um carrega também o alelo dominante B: ambos são heterozigotos Bb." }
  ] },
  "cie-10": { q: [
    { t:"fix", q:"Segundo a teoria da seleção natural de Darwin, as espécies evoluem porque:", opts:["os indivíduos se transformam por esforço durante a vida e transmitem essas mudanças aos filhos","os indivíduos com características mais favoráveis ao ambiente sobrevivem mais e deixam mais descendentes","todas as espécies evoluem em direção à perfeição","o ambiente cria novas características nos organismos"], a:1, exp:"A seleção natural age sobre variações que já existem na população: quem está melhor adaptado ao ambiente sobrevive e se reproduz mais, aumentando a frequência dessas características." },
    { t:"fix", q:"Os fósseis são importantes para o estudo da evolução porque:", opts:["são restos ou vestígios de seres que viveram no passado e mostram como as espécies mudaram ao longo do tempo","provam que as espécies nunca se modificaram","são rochas formadas sem participação de seres vivos","mostram apenas os animais que existem hoje"], a:0, exp:"Fósseis são restos (ossos, conchas) ou vestígios (pegadas) preservados em rochas. Comparando fósseis de épocas diferentes, percebe-se a transformação gradual das espécies." },
    { t:"apl", q:"Um paciente interrompeu o antibiótico antes do fim do tratamento, e a infecção voltou mais forte. Do ponto de vista evolutivo, isso aconteceu porque:", opts:["o antibiótico criou bactérias novas no organismo","as bactérias se esforçaram para resistir ao remédio","as bactérias mais resistentes sobreviveram às doses parciais e se multiplicaram, tornando a população resistente","o remédio enfraqueceu o sistema de defesa do paciente"], a:2, exp:"Já existiam, por acaso, bactérias mais resistentes na população. O tratamento incompleto eliminou as sensíveis e selecionou as resistentes, que se multiplicaram — seleção natural em ação." },
    { t:"apl", q:"Nas ilhas Galápagos, Darwin observou tentilhões com bicos de formatos diferentes em cada ilha: grossos onde havia sementes duras, finos onde havia insetos. A explicação darwinista para essa diversidade é que:", opts:["cada pássaro escolheu o formato do próprio bico conforme a dieta","os bicos mudaram durante a vida de cada ave para facilitar a alimentação","todas as ilhas tinham o mesmo alimento, então os bicos variaram ao acaso","em cada ilha, as aves com bicos adequados ao alimento disponível sobreviveram e se reproduziram mais"], a:3, exp:"A variação nos bicos já existia; em cada ambiente, a seleção natural favoreceu o formato mais útil para obter alimento, e essas aves deixaram mais descendentes." },
    { t:"des", q:"Antes da Revolução Industrial, na Inglaterra, as mariposas claras eram as mais comuns, pois se camuflavam nos troncos claros das árvores. Com a poluição, os troncos escureceram e as mariposas escuras passaram a predominar. A explicação correta para essa mudança é:", opts:["as mariposas claras escureceram para se esconder dos predadores e transmitiram a nova cor aos filhotes","a variação de cor já existia; com os troncos escuros, as claras ficaram visíveis e foram mais predadas, enquanto as escuras sobreviveram e deixaram mais descendentes","a fuligem entrou no DNA das mariposas e mudou sua cor","as mariposas claras migraram para outro país"], a:1, exp:"O ambiente mudou, mas a seleção agiu sobre variações que já existiam: os predadores passaram a enxergar as claras, e as escuras sobreviveram mais. Indivíduos não mudam de cor por necessidade — essa era a ideia de Lamarck, já superada." }
  ] },
  "cie-11": { q: [
    { t:"fix", q:"Nas células eucarióticas, como as do nosso corpo, o DNA está localizado principalmente:", opts:["nas mitocôndrias, que produzem energia","nos ribossomos, que produzem proteínas","na membrana celular, que protege a célula","no núcleo, organizado em cromossomos"], a:3, exp:"No núcleo, o DNA se enrola e se organiza em cromossomos, que guardam os genes. (Existe também um pouco de DNA nas mitocôndrias, mas a maior parte está no núcleo.)" },
    { t:"apl", q:"Gêmeos idênticos (univitelinos) nascem do mesmo zigoto. Se um deles pratica musculação e fica forte, enquanto o outro é sedentário, essa diferença corporal mostra que:", opts:["o genótipo deles mudou com o exercício","gêmeos idênticos não têm o mesmo DNA","o fenótipo depende do genótipo e também das influências do ambiente e do estilo de vida","apenas o gêmeo forte herdou bons genes"], a:2, exp:"Os gêmeos idênticos têm o mesmo genótipo, mas o fenótipo (a característica expressa) sofre influência do ambiente: alimentação, exercício e hábitos modificam o corpo." },
    { t:"apl", q:"Um homem sofreu uma mutação genética em uma célula da pele, causada por exposição ao sol. Essa mutação poderá ser transmitida a seus filhos?", opts:["Não, pois só mutações em células reprodutivas (gametas) são transmitidas aos descendentes","Sim, pois toda mutação passa de pais para filhos","Sim, desde que a mutação seja dominante","Não, pois mutações nunca ocorrem em seres humanos"], a:0, exp:"Mutações em células do corpo (somáticas) afetam apenas a pessoa. Para ser herdada, a mutação precisa estar nos gametas (espermatozoide ou óvulo) que formam o embrião." },
    { t:"des", q:"Em coelhos, a cor preta do pelo (P) é dominante sobre a branca (p). Cruzaram-se dois coelhos pretos heterozigotos (Pp × Pp). A chance de nascer um filhote branco (pp) é de:", opts:["50%","25%","75%","0%, pois os pais são pretos"], a:1, exp:"As combinações possíveis são PP, Pp, Pp e pp. Apenas uma das quatro (25%) resulta em pp, que é branco. Os outros três genótipos têm pelo preto." },
    { t:"des", q:"Um hospital notificou o surgimento de uma superbactéria resistente a vários antibióticos. Reunindo os conceitos de genética e evolução, o processo que melhor explica o surgimento dela é:", opts:["os antibióticos ensinaram as bactérias a se defender, e elas transmitiram o aprendizado","as bactérias decidiram criar resistência para sobreviver nos hospitais","o ambiente hospitalar transformou vírus em bactérias resistentes","mutações ao acaso geraram resistência em algumas bactérias; o uso intenso de antibióticos eliminou as sensíveis e selecionou as resistentes, que se multiplicaram"], a:3, exp:"São dois passos: primeiro, mutações aleatórias criaram a resistência; depois, os antibióticos agiram como agente de seleção, matando as sensíveis e deixando as resistentes se reproduzirem. É a evolução por seleção natural." }
  ] }
});
