/* Banco de questões — Matemática (8º/9º ano) — protótipo GTA: Grande Trilha do Aprendizado */
window.QUESTOES = window.QUESTOES || {};
Object.assign(window.QUESTOES, {
  "mat-0": { q: [
    { t:"fix", q:"Aplicando o quadrado da soma, quanto é (x + 5)²?", opts:["x² + 25","x² + 10x + 25","x² + 5x + 25","x² + 10x + 10"], a:1, exp:"(x + 5)² = x² + 2 × x × 5 + 5² = x² + 10x + 25. O erro comum é esquecer o termo do meio, 10x." },
    { t:"fix", q:"Qual é a forma fatorada de x² − 9?", opts:["(x − 3)²","(x + 9)(x − 1)","(x + 3)(x − 3)","x(x − 9)"], a:2, exp:"x² − 9 é uma diferença de quadrados: x² − 3² = (x + 3)(x − 3)." },
    { t:"apl", q:"Um terreno retangular tem lados que medem (x + 3) m e (x − 3) m. Qual expressão representa sua área?", opts:["x² − 9","x² − 6x + 9","x² + 9","2x − 6"], a:0, exp:"A área é o produto da soma pela diferença: (x + 3)(x − 3) = x² − 9." },
    { t:"apl", q:"Para calcular 102² sem calculadora, Téo usou o produto notável (100 + 2)². Qual resultado ele encontrou?", opts:["10400","10204","10004","10404"], a:3, exp:"(100 + 2)² = 10000 + 2 × 100 × 2 + 4 = 10000 + 400 + 4 = 10404." },
    { t:"des", q:"Sabendo que (x + y)² = 100 e que x × y = 21, qual é o valor de x² + y²?", opts:["79","142","58","121"], a:2, exp:"Expandindo: x² + 2xy + y² = 100. Como 2xy = 2 × 21 = 42, temos x² + y² = 100 − 42 = 58." }
  ] },
  "mat-1": { q: [
    { t:"fix", q:"Na equação x² − 5x + 6 = 0, quais são os coeficientes a, b e c?", opts:["a = 1, b = 5, c = 6","a = 0, b = −5, c = 6","a = 1, b = −5, c = −6","a = 1, b = −5, c = 6"], a:3, exp:"Na forma ax² + bx + c = 0, temos a = 1 (coeficiente de x²), b = −5 (coeficiente de x) e c = 6 (termo independente)." },
    { t:"fix", q:"Qual é o valor do discriminante Δ da equação x² + 3x − 4 = 0?", opts:["−7","25","7","9"], a:1, exp:"Δ = b² − 4ac = 3² − 4 × 1 × (−4) = 9 + 16 = 25. Cuidado com o sinal: menos vezes menos dá mais." },
    { t:"apl", q:"O produto de dois números naturais consecutivos é 156. Quais são esses números?", opts:["11 e 12","13 e 14","12 e 13","10 e 15"], a:2, exp:"Chamando o menor de n: n(n + 1) = 156, ou seja, n² + n − 156 = 0. Com Δ = 625 e √625 = 25, temos n = (−1 + 25) ÷ 2 = 12. Os números são 12 e 13, pois 12 × 13 = 156." },
    { t:"apl", q:"Um quadrado tem área de 81 cm². Se seu lado mede (x − 2) cm, qual é o valor de x?", opts:["11","9","83","7"], a:0, exp:"(x − 2)² = 81, logo x − 2 = 9 (a medida do lado é positiva). Portanto, x = 11." },
    { t:"des", q:"Para que valor de k a equação x² − 10x + k = 0 tem duas raízes reais iguais?", opts:["10","25","−25","100"], a:1, exp:"Raízes iguais exigem Δ = 0. Então (−10)² − 4 × 1 × k = 0, ou seja, 100 − 4k = 0, e k = 25." }
  ] },
  "mat-2": { q: [
    { t:"fix", q:"Qual par ordenado (x, y) é a solução do sistema x + y = 10 e x − y = 4?", opts:["(6, 4)","(7, 3)","(5, 5)","(8, 2)"], a:1, exp:"Somando as equações: 2x = 14, logo x = 7. Substituindo: 7 + y = 10, então y = 3. De fato, 7 − 3 = 4." },
    { t:"fix", q:"Resolvendo pelo método da substituição o sistema y = 2x e x + y = 9, qual é o valor de x?", opts:["6","2","9","3"], a:3, exp:"Substituindo y por 2x na segunda equação: x + 2x = 9, ou seja, 3x = 9, e x = 3." },
    { t:"apl", q:"Em um estacionamento há carros e motos, totalizando 20 veículos e 58 rodas. Quantos carros há no estacionamento?", opts:["11","9","10","12"], a:1, exp:"Com c carros e m motos: c + m = 20 e 4c + 2m = 58. Da primeira, 2c + 2m = 40; subtraindo, 2c = 18, logo c = 9 carros (e 11 motos)." },
    { t:"apl", q:"Em uma lanchonete, 2 lanches e 1 suco custam R$ 21,00, enquanto 1 lanche e 2 sucos custam R$ 12,00. Qual é o preço de um lanche?", opts:["R$ 7,00","R$ 8,00","R$ 10,00","R$ 11,00"], a:2, exp:"Com L e S: 2L + S = 21 e L + 2S = 12. Dobrando a primeira: 4L + 2S = 42; subtraindo a segunda: 3L = 30, logo o lanche custa R$ 10,00 (e o suco, R$ 1,00)." },
    { t:"des", q:"A soma de dois números é 25, e o dobro do primeiro somado ao triplo do segundo é 60. Quais são esses números?", opts:["15 e 10","10 e 15","12 e 13","18 e 7"], a:0, exp:"Com x + y = 25 e 2x + 3y = 60: da primeira, 2x + 2y = 50; subtraindo da segunda, y = 10, e então x = 15. Conferindo: 2 × 15 + 3 × 10 = 60." }
  ] },
  "mat-3": { q: [
    { t:"fix", q:"Qual é a forma fatorada de x² − 16?", opts:["(x − 4)²","(x + 8)(x − 2)","(x + 4)(x − 4)","(x + 16)(x − 1)"], a:2, exp:"x² − 16 é diferença de quadrados: x² − 4² = (x + 4)(x − 4)." },
    { t:"apl", q:"O quadrado de um número positivo, menos o triplo desse número, é igual a 28. Qual é esse número?", opts:["5","7","8","6"], a:1, exp:"x² − 3x = 28, ou seja, x² − 3x − 28 = 0. Com Δ = 121 e √121 = 11: x = (3 + 11) ÷ 2 = 7 (a outra raiz, −4, é negativa). Conferindo: 49 − 21 = 28." },
    { t:"apl", q:"Em um cercado há galinhas e coelhos: 35 cabeças e 100 pés ao todo. Quantos coelhos há no cercado?", opts:["20","10","15","25"], a:2, exp:"Com g galinhas e c coelhos: g + c = 35 e 2g + 4c = 100. Da primeira, 2g + 2c = 70; subtraindo da segunda, 2c = 30, logo c = 15 coelhos (e 20 galinhas)." },
    { t:"des", q:"Se (x + 3)² − (x − 3)² = 48, qual é o valor de x?", opts:["4","6","8","12"], a:0, exp:"Expandindo: (x² + 6x + 9) − (x² − 6x + 9) = 12x. Então 12x = 48, e x = 4. Conferindo: 7² − 1² = 49 − 1 = 48." },
    { t:"des", q:"Em um cinema, o ingresso inteiro custa R$ 24,00 e a meia-entrada, R$ 12,00. Foram vendidos 80 ingressos, com arrecadação de R$ 1.560,00. Quantas meias-entradas foram vendidas?", opts:["50","40","20","30"], a:3, exp:"Com i inteiras e m meias: i + m = 80 e 24i + 12m = 1560. Da primeira, 12i + 12m = 960; subtraindo, 12i = 600, logo i = 50 e m = 30 meias-entradas." }
  ] },
  "mat-4": { q: [
    { t:"fix", q:"O que afirma o teorema de Pitágoras em um triângulo retângulo?", opts:["a soma dos catetos é igual à hipotenusa","a hipotenusa é igual à soma dos quadrados dos catetos","o quadrado da hipotenusa é igual à soma dos quadrados dos catetos","os dois catetos têm sempre a mesma medida"], a:2, exp:"O teorema diz que, sendo a a hipotenusa e b e c os catetos, vale a² = b² + c². Ele só vale para triângulos retângulos." },
    { t:"fix", q:"Um triângulo retângulo tem catetos de 6 cm e 8 cm. Qual é a medida da hipotenusa?", opts:["10 cm","14 cm","12 cm","9 cm"], a:0, exp:"h² = 6² + 8² = 36 + 64 = 100, logo h = √100 = 10 cm. O erro comum é somar 6 + 8 = 14." },
    { t:"apl", q:"Um campo retangular mede 30 m por 40 m. Qual é a distância em linha reta entre dois cantos opostos (a diagonal do campo)?", opts:["70 m","60 m","45 m","50 m"], a:3, exp:"A diagonal é a hipotenusa de um triângulo de catetos 30 e 40: d² = 900 + 1600 = 2500, logo d = 50 m." },
    { t:"apl", q:"Uma escada de 5 m está apoiada no alto de um muro, e sua base fica a 3 m da parede. A que altura do chão está o topo da escada?", opts:["2 m","4 m","3,5 m","4,5 m"], a:1, exp:"A escada é a hipotenusa: 5² = 3² + h², então h² = 25 − 9 = 16, e h = 4 m." },
    { t:"des", q:"Um triângulo tem lados de 9 cm, 12 cm e 15 cm. Esse triângulo é retângulo?", opts:["Não, pois 9 + 12 é diferente de 15","Não, pois 9² + 12² é diferente de 15²","Sim, pois 9² + 12² = 15²","Sim, pois 15 é o maior lado"], a:2, exp:"Testando o maior lado como hipotenusa: 9² + 12² = 81 + 144 = 225 = 15². Como vale a relação de Pitágoras, o triângulo é retângulo." }
  ] },
  "mat-5": { q: [
    { t:"fix", q:"Quando dois triângulos são semelhantes?", opts:["quando têm ângulos correspondentes iguais e lados correspondentes proporcionais","quando têm todos os lados com a mesma medida","quando têm exatamente a mesma área","quando têm o mesmo perímetro"], a:0, exp:"Na semelhança, a forma se mantém: ângulos iguais e lados proporcionais. Áreas ou perímetros iguais não garantem a mesma forma." },
    { t:"fix", q:"Dois triângulos semelhantes têm razão de semelhança 2 (do menor para o maior). Se um lado do menor mede 3 cm, quanto mede o lado correspondente do maior?", opts:["5 cm","9 cm","6 cm","1,5 cm"], a:2, exp:"Multiplica-se pela razão: 3 × 2 = 6 cm. A razão de semelhança atua sobre todos os lados correspondentes." },
    { t:"apl", q:"Para medir a altura de um poste, Bia observou as sombras no mesmo horário: a do poste mede 6 m e a de uma vara de 1,5 m mede 2 m. Qual é a altura do poste?", opts:["4,5 m","8 m","3 m","9 m"], a:0, exp:"Os triângulos são semelhantes (mesmo ângulo do Sol): h ÷ 1,5 = 6 ÷ 2 = 3, logo h = 1,5 × 3 = 4,5 m." },
    { t:"apl", q:"Em um mapa de escala 1:50.000, a distância entre duas cidades é de 8 cm. Qual é a distância real entre elas?", opts:["40 km","4 km","400 m","400 km"], a:1, exp:"Cada centímetro vale 50.000 cm: 8 × 50.000 = 400.000 cm = 4.000 m = 4 km." },
    { t:"des", q:"No triângulo ABC, uma reta paralela ao lado BC divide o lado AB em segmentos de 4 cm e 6 cm e o lado AC em segmentos de 6 cm e x. Pelo teorema de Tales, qual é o valor de x?", opts:["8 cm","10 cm","12 cm","9 cm"], a:3, exp:"Retas paralelas criam segmentos proporcionais: 4 ÷ 6 = 6 ÷ x. Então 4x = 36, e x = 9 cm." }
  ] },
  "mat-6": { q: [
    { t:"fix", q:"Qual é a área de um triângulo de base 10 cm e altura 6 cm?", opts:["60 cm²","30 cm²","16 cm²","32 cm²"], a:1, exp:"Área do triângulo = (base × altura) ÷ 2 = (10 × 6) ÷ 2 = 30 cm². O erro comum é esquecer de dividir por 2." },
    { t:"fix", q:"Usando π ≈ 3,14, qual é a área de um círculo de raio 5 cm?", opts:["78,5 cm²","31,4 cm²","15,7 cm²","157 cm²"], a:0, exp:"Área = π × r² = 3,14 × 5² = 3,14 × 25 = 78,5 cm². Atenção: é o raio ao quadrado, não o raio vezes 2." },
    { t:"apl", q:"Um terreno em forma de trapézio tem bases de 12 m e 8 m e altura de 5 m. Qual é a área desse terreno?", opts:["100 m²","60 m²","25 m²","50 m²"], a:3, exp:"Área do trapézio = (base maior + base menor) × altura ÷ 2 = (12 + 8) × 5 ÷ 2 = 50 m²." },
    { t:"apl", q:"Uma parede retangular de 4 m por 2,5 m tem uma porta de 1 m por 2 m, que não será pintada. Quantos metros quadrados serão pintados?", opts:["10 m²","9 m²","8 m²","7,5 m²"], a:2, exp:"Área da parede: 4 × 2,5 = 10 m². Área da porta: 1 × 2 = 2 m². Serão pintados 10 − 2 = 8 m²." },
    { t:"des", q:"Um retângulo de 12 cm por 5 cm tem a mesma área de um triângulo de base 15 cm. Qual é a altura desse triângulo?", opts:["4 cm","6 cm","10 cm","8 cm"], a:3, exp:"Área do retângulo: 12 × 5 = 60 cm². No triângulo: (15 × h) ÷ 2 = 60, então 15h = 120, e h = 8 cm." }
  ] },
  "mat-7": { q: [
    { t:"fix", q:"Um triângulo retângulo tem hipotenusa de 13 cm e um cateto de 5 cm. Quanto mede o outro cateto?", opts:["8 cm","18 cm","12 cm","√194 cm"], a:2, exp:"c² = 13² − 5² = 169 − 25 = 144, logo c = 12 cm. O erro comum é somar os quadrados em vez de subtrair." },
    { t:"apl", q:"Um prédio projeta uma sombra de 15 m no chão. No mesmo instante, um homem de 1,8 m projeta uma sombra de 2,4 m. Qual é a altura do prédio?", opts:["11,25 m","12,5 m","9 m","13,5 m"], a:0, exp:"Por semelhança de triângulos: h ÷ 1,8 = 15 ÷ 2,4 = 6,25. Então h = 1,8 × 6,25 = 11,25 m." },
    { t:"apl", q:"Uma sala retangular de 6 m por 4 m será coberta com cerâmicas quadradas de 50 cm de lado. Quantas cerâmicas serão necessárias?", opts:["48","24","192","96"], a:3, exp:"Área da sala: 24 m² = 240.000 cm². Cada cerâmica tem 50 × 50 = 2.500 cm². Então 240.000 ÷ 2.500 = 96 cerâmicas." },
    { t:"des", q:"Um triângulo retângulo tem catetos de 9 cm e 12 cm. Qual é a área de um quadrado construído sobre a hipotenusa desse triângulo?", opts:["15 cm²","225 cm²","150 cm²","441 cm²"], a:1, exp:"O lado do quadrado é a hipotenusa: h² = 9² + 12² = 81 + 144 = 225. A área do quadrado é justamente h² = 225 cm²." },
    { t:"des", q:"Dois triângulos semelhantes têm razão de semelhança 1:3 (do menor para o maior). Se a área do menor é 8 cm², qual é a área do maior?", opts:["24 cm²","64 cm²","32 cm²","72 cm²"], a:3, exp:"A razão entre as áreas é o quadrado da razão de semelhança: 3² = 9. Então a área maior é 8 × 9 = 72 cm²." }
  ] },
  "mat-8": { q: [
    { t:"fix", q:"Na função f(x) = 3x + 2, qual é o valor de f(4)?", opts:["9","24","14","12"], a:2, exp:"Substituindo x por 4: f(4) = 3 × 4 + 2 = 12 + 2 = 14." },
    { t:"fix", q:"Na função afim f(x) = ax + b, o que o coeficiente b representa no gráfico?", opts:["a taxa de variação da função","o ponto onde a reta corta o eixo y","o valor de x quando y é zero","o valor máximo da função"], a:1, exp:"Quando x = 0, temos f(0) = b. Por isso b é o valor onde a reta cruza o eixo vertical (eixo y)." },
    { t:"apl", q:"Um táxi cobra R$ 5,00 de bandeirada mais R$ 2,50 por quilômetro rodado. Qual função representa o preço p em função da distância d?", opts:["p(d) = 2,5d + 5","p(d) = 5d + 2,5","p(d) = 7,5d","p(d) = 5d − 2,5"], a:0, exp:"O valor fixo (R$ 5,00) é o termo b, e o valor por quilômetro (R$ 2,50) multiplica a distância: p(d) = 2,5d + 5." },
    { t:"apl", q:"Nesse táxi, que cobra R$ 5,00 de bandeirada mais R$ 2,50 por quilômetro, quanto custa uma corrida de 12 km?", opts:["R$ 30,00","R$ 25,00","R$ 40,00","R$ 35,00"], a:3, exp:"p(12) = 2,5 × 12 + 5 = 30 + 5 = 35. A corrida custa R$ 35,00." },
    { t:"des", q:"O gráfico de uma função afim passa pelos pontos (0, 4) e (2, 10). Qual é a lei dessa função?", opts:["f(x) = 3x + 4","f(x) = 5x + 4","f(x) = 4x + 3","f(x) = 2x + 10"], a:0, exp:"Como f(0) = 4, temos b = 4. Depois: f(2) = 2a + 4 = 10, então 2a = 6 e a = 3. A lei é f(x) = 3x + 4." }
  ] },
  "mat-9": { q: [
    { t:"fix", q:"O gráfico de uma função quadrática f(x) = ax² + bx + c (com a diferente de zero) é sempre uma:", opts:["reta","circunferência","hipérbole","parábola"], a:3, exp:"Toda função do 2º grau tem gráfico em forma de parábola, com concavidade para cima (a > 0) ou para baixo (a < 0)." },
    { t:"fix", q:"Na função f(x) = x² − 4x + 3, quanto vale f(2)?", opts:["−1","1","3","7"], a:0, exp:"f(2) = 2² − 4 × 2 + 3 = 4 − 8 + 3 = −1. Valores negativos da função são comuns e válidos." },
    { t:"apl", q:"Uma bola lançada para cima tem altura dada por h(t) = −t² + 6t, com t em segundos e h em metros. Em que instante ela atinge a altura máxima?", opts:["6 s","2 s","3 s","9 s"], a:2, exp:"O instante máximo é a coordenada x do vértice: t = −b ÷ (2a) = −6 ÷ (2 × (−1)) = 3 segundos." },
    { t:"apl", q:"Nesse mesmo lançamento, com h(t) = −t² + 6t, qual é a altura máxima que a bola atinge?", opts:["6 m","9 m","12 m","3 m"], a:1, exp:"A altura máxima ocorre em t = 3: h(3) = −3² + 6 × 3 = −9 + 18 = 9 metros." },
    { t:"des", q:"Em quais pontos a parábola f(x) = x² − 6x + 5 corta o eixo x?", opts:["x = 1 e x = 5","x = −1 e x = −5","x = 2 e x = 3","x = 0 e x = 6"], a:0, exp:"Cortar o eixo x significa f(x) = 0. Resolvendo x² − 6x + 5 = 0: Δ = 36 − 20 = 16, √16 = 4, e x = (6 ± 4) ÷ 2, ou seja, x = 1 e x = 5." }
  ] },
  "mat-10": { q: [
    { t:"fix", q:"Em um gráfico de linhas que mostra a temperatura de uma cidade ao longo de um dia, o que indica o ponto mais alto da linha?", opts:["a temperatura máxima do dia e o horário em que ela ocorreu","a temperatura média do dia","o horário em que começou a esfriar","a temperatura no início do dia"], a:0, exp:"No gráfico de linhas, cada ponto liga um horário (eixo x) a uma temperatura (eixo y). O ponto mais alto mostra o maior valor de y e quando ele aconteceu." },
    { t:"fix", q:"Em um gráfico de setores (tipo pizza), um setor representa 25% de um total de 200 alunos pesquisados. Quantos alunos esse setor representa?", opts:["25","50","75","100"], a:1, exp:"25% de 200 = 25 ÷ 100 × 200 = 50 alunos. No gráfico de setores, cada fatia é proporcional à sua porcentagem do total." },
    { t:"apl", q:"Uma tabela mostra a distância percorrida por um ciclista: 20 km às 9h, 40 km às 10h e 60 km às 11h. Qual é a velocidade média do ciclista nesse período?", opts:["20 km/h","10 km/h","40 km/h","60 km/h"], a:0, exp:"A cada hora a distância aumenta 20 km, então a velocidade média é de 20 km/h, constante ao longo do período." },
    { t:"apl", q:"O gráfico de barras mostra o saldo de uma conta no fim de cada mês: R$ 200 em janeiro, R$ 150 em fevereiro, R$ 100 em março e R$ 100 em abril. Em qual mês o saldo ficou igual ao do mês anterior?", opts:["fevereiro","março","abril","janeiro"], a:2, exp:"De março para abril o saldo passou de R$ 100 para R$ 100, sem variação. Nos meses anteriores, o saldo sempre caiu." },
    { t:"des", q:"Uma tabela registra a população de uma cidade: 10.000 habitantes em 2020, 12.000 em 2021 e 14.400 em 2022. Se o mesmo padrão de crescimento continuar, quantos habitantes a cidade terá em 2023?", opts:["16.800","16.400","15.840","17.280"], a:3, exp:"O padrão é multiplicar por 1,2 (aumento de 20% ao ano), não somar 2.000. Então 14.400 × 1,2 = 17.280 habitantes." }
  ] },
  "mat-11": { q: [
    { t:"fix", q:"Uma função afim f(x) = ax + b é crescente quando:", opts:["a é maior que zero","a é menor que zero","b é maior que zero","b é igual a zero"], a:0, exp:"É o coeficiente a (taxa de variação) que define a inclinação: a > 0, função crescente; a < 0, decrescente. O b só desloca a reta." },
    { t:"apl", q:"Uma locadora cobra R$ 20,00 de taxa fixa mais R$ 3,00 por dia de aluguel de um jogo. Se Carlos pagou R$ 41,00, por quantos dias ele ficou com o jogo?", opts:["5 dias","7 dias","6 dias","8 dias"], a:1, exp:"Montando a função: 3d + 20 = 41. Então 3d = 21, e d = 7 dias." },
    { t:"apl", q:"O lucro mensal de uma loja, em centenas de reais, é dado por L(x) = −x² + 20x, onde x é o preço de um produto em reais. Qual preço gera o lucro máximo?", opts:["R$ 20,00","R$ 5,00","R$ 15,00","R$ 10,00"], a:3, exp:"O máximo ocorre no vértice: x = −b ÷ (2a) = −20 ÷ (2 × (−1)) = 10. O preço deve ser R$ 10,00." },
    { t:"des", q:"Qual é o vértice da parábola f(x) = x² − 4?", opts:["(0, −4)","(0, 4)","(−4, 0)","(2, 0)"], a:0, exp:"Como b = 0, a coordenada x do vértice é 0. Calculando: f(0) = 0² − 4 = −4. O vértice é o ponto (0, −4)." },
    { t:"des", q:"Duas caixas-d'água foram registradas em um gráfico: a caixa A começa com 100 litros e perde 5 litros por minuto; a caixa B começa com 40 litros e ganha 5 litros por minuto. Depois de quantos minutos as duas terão a mesma quantidade de água?", opts:["5 min","8 min","6 min","10 min"], a:2, exp:"As funções são A(t) = 100 − 5t e B(t) = 40 + 5t. Igualando: 100 − 5t = 40 + 5t, então 60 = 10t, e t = 6 minutos (as duas ficam com 70 litros)." }
  ] }
});
