/* Banco de questões — Língua Portuguesa (8º/9º ano) — protótipo GTA: Grande Trilha do Aprendizado */
window.QUESTOES = window.QUESTOES || {};
Object.assign(window.QUESTOES, {
  "por-0": { q: [
    { t:"fix", q:"Qual característica é essencial ao gênero notícia?", opts:["linguagem poética, com rimas e metáforas","informação objetiva sobre um fato recente, verdadeiro e de interesse coletivo","enredo ficcional com personagens inventados","opinião pessoal do repórter em todos os parágrafos"], a:1, exp:"A notícia informa com objetividade um fato real e recente que interessa ao público. Opinião fica de fora — esse é o espaço do editorial e da crônica." },
    { t:"fix", q:"No jornalismo, o que é o lead?", opts:["o último parágrafo, com o desfecho emocionante","o título em letras maiúsculas","a assinatura do jornalista no fim do texto","o primeiro parágrafo da notícia, que resume as informações essenciais: o quê, quem, quando, onde, como e por quê"], a:3, exp:"O lead abre a notícia respondendo às perguntas fundamentais. Quem lê só o lead já fica sabendo do essencial — técnica chamada de pirâmide invertida." },
    { t:"apl", q:"Leia o lead: «Um vazamento em uma tubulação deixou cerca de 2 mil moradores do bairro Vila Nova sem água potável na manhã de ontem, segundo a companhia de saneamento. O serviço deve ser normalizado até sexta-feira.» Qual informação essencial NÃO aparece nesse lead?", opts:["por que a tubulação se rompeu, ou seja, a causa do problema","o que aconteceu","quantas pessoas foram afetadas","quando ocorreu o problema"], a:0, exp:"O lead informa o fato (vazamento), o local, a data e o número de afetados, mas não explica a causa do rompimento — o «por quê» ficou sem resposta." },
    { t:"apl", q:"Um jornal publicou dois textos sobre a mesma enchente. O texto I resume o fato em cinco linhas. O texto II tem três páginas, com entrevistas de moradores, histórico de enchentes na cidade e análise de um engenheiro hidrólogo. O texto II é:", opts:["uma notícia","um editorial","uma reportagem","um anúncio publicitário"], a:2, exp:"A reportagem aprofunda o fato com apuração, fontes variadas e contexto. A notícia é mais curta e direta, e o editorial traz a opinião do jornal." },
    { t:"des", q:"Na pirâmide invertida, as informações mais importantes vêm no início e as complementares, no final. Leia a notícia: «P1: A biblioteca municipal reabriu ontem, após dois anos de reforma, com acervo ampliado e sala de estudos 24 horas. P2: A reforma custou R$ 1,2 milhão, vindos de um convênio estadual, segundo a prefeitura. P3: A biblioteca foi fundada em 1968 por um grupo de professores e já funcionou em três endereços diferentes.» Se o editor precisar cortar o último parágrafo por falta de espaço, o leitor deixará de saber:", opts:["quando a biblioteca reabriu","quanto custou a reforma","de onde veio o dinheiro","dados históricos da instituição, que são a informação menos essencial da notícia"], a:3, exp:"O histórico de 1968 é complementar e por isso ficou no fim: pode ser cortado sem comprometer a informação principal, que é a reabertura da biblioteca." }
  ] },
  "por-1": { q: [
    { t:"fix", q:"Qual é a diferença entre fato e opinião?", opts:["o fato é sempre positivo e a opinião, sempre negativa","o fato é o que a maioria acredita, e a opinião é o que poucos pensam","o fato pode ser verificado e comprovado; a opinião expressa um juízo de valor, uma avaliação pessoal","o fato aparece em livros e a opinião, somente na internet"], a:2, exp:"Fato é verificável: dá para checar em documentos, dados e registros. Opinião é uma avaliação subjetiva, que varia de pessoa para pessoa." },
    { t:"fix", q:"Qual destas marcas linguísticas costuma indicar a presença de opinião num texto?", opts:["adjetivos avaliativos e expressões como «na minha opinião», «infelizmente», «deveria»","datas e estatísticas","nomes próprios de pessoas e cidades","aspas reproduzindo a fala de um entrevistado"], a:0, exp:"Palavras como «infelizmente», «absurdo», «deveria» carregam avaliação de quem escreve. Datas, estatísticas e nomes próprios, ao contrário, são dados objetivos." },
    { t:"apl", q:"Leia as frases sobre um jogo da seleção: I. A seleção venceu por 2 a 0, com gols no segundo tempo. II. Foi a partida mais emocionante da história do estádio. III. O ingresso mais barato custou R$ 80. IV. O time visitante, sem dúvida, jogou de forma covarde. São OPINIÕES as frases:", opts:["I e III","I e II","III e IV","II e IV"], a:3, exp:"«Mais emocionante da história» e «covarde» são juízos de valor, impossíveis de comprovar. Placar e preço de ingresso são fatos verificáveis." },
    { t:"apl", q:"Um jornal noticiou: «A prefeitura inaugurou ontem a terceira estação de tratamento de esgoto da cidade.» No editorial da mesma edição, lê-se: «A inauguração chega tarde: a população merecia esse investimento há pelo menos uma década.» A frase do editorial expressa opinião porque:", opts:["informa a data da inauguração","avalia o fato com juízo crítico («chega tarde», «merecia»), o que é próprio dos textos de opinião","foi escrita pelo prefeito da cidade","usa linguagem técnica de engenharia"], a:1, exp:"O editorial não se limita a informar: avalia o fato como tardio e defende uma tese. É por isso que editoriais e notícias ficam em seções separadas do jornal." },
    { t:"des", q:"Leia: «Segundo o IBGE, o desmatamento na região cresceu 12% em um ano. Como sempre, os produtores locais são os únicos culpados por esse desastre.» Sobre o trecho, é correto afirmar:", opts:["as duas frases são fatos comprováveis","as duas frases são apenas opiniões","a primeira frase é fato (dado verificável, com fonte identificada), e a segunda é opinião que se disfarça de fato ao generalizar a culpa com «como sempre» e «únicos»","a primeira frase é opinião e a segunda é fato"], a:2, exp:"O dado do IBGE pode ser conferido; já culpar «os únicos» culpados «como sempre» é generalização avaliativa. Opinião com roupagem de fato é um recurso comum — e perigoso." }
  ] },
  "por-2": { q: [
    { t:"fix", q:"A coesão referencial acontece quando:", opts:["um termo retoma ou antecipa outro elemento do texto, como em «Maria chegou. Ela estava cansada.»","o texto usa palavras difíceis e rebuscadas","as frases são propositalmente longas","o autor repete a mesma palavra em todas as frases"], a:0, exp:"Na coesão referencial, pronomes, sinônimos e expressões retomam (ou antecipam) referentes, ligando as partes do texto sem repetições desnecessárias." },
    { t:"fix", q:"Em «Ela já nasceu sabendo nadar: a filha da pescadora surpreendeu a todos», o pronome «ela» antecipa uma informação que só aparece depois. Esse recurso, ao contrário da retomada comum (anafórica), é chamado de:", opts:["elipse","pleonasmo","referência catafórica","polissemia"], a:2, exp:"Na catáfora, o termo referente aparece ANTES daquilo a que se refere — o pronome anuncia algo que o texto ainda vai apresentar." },
    { t:"apl", q:"Leia o trecho de uma notícia: «O prefeito visitou o hospital de campanha e anunciou que ele será ampliado, com mais 40 leitos.» No contexto, o pronome «ele» retoma:", opts:["o prefeito","o hospital de campanha","a visita","o anúncio"], a:1, exp:"O contexto mostra que o que será ampliado é o hospital. Sem as informações ao redor, o pronome ficaria ambíguo — é o texto que resolve a referência." },
    { t:"apl", q:"Leia: «Um cachorro caramelo foi adotado ontem no abrigo municipal. O vira-lata passou dois anos esperando uma família. O animal agora divide o sofá com dois gatos.» As expressões «o vira-lata» e «o animal» foram usadas para:", opts:["apresentar três cachorros diferentes","confundir o leitor de propósito","criar suspense sobre o final da história","retomar o mesmo referente sem repetir a palavra, deixando o texto mais fluente"], a:3, exp:"A retomada por sinônimos e hiperônimos («cachorro» → «vira-lata» → «animal») mantém a coesão e evita a repetição cansativa do mesmo termo." },
    { t:"des", q:"Leia o trecho de uma carta de reclamação: «O técnico veio consertar o ar-condicionado do gerente, mas ele não estava, e o serviço ficou para a próxima semana.» O problema de coesão do trecho é:", opts:["o uso excessivo de conectivos","o pronome «ele» é ambíguo: pode se referir ao técnico ou ao gerente, e essa dúvida muda completamente o sentido da reclamação","a repetição da palavra «serviço»","a falta de pontuação entre as orações"], a:1, exp:"Dois referentes possíveis disputam o pronome. Para corrigir, seria preciso reescrever, por exemplo: «mas o gerente não estava». Coesão falha gera mal-entendido." }
  ] },
  "por-3": { q: [
    { t:"fix", q:"Você é o diretor de um jornal e treina novos repórteres. Qual conjunto de perguntas um lead completo deve responder?", opts:["quem ganhou e quem perdeu","o que o repórter achou do fato","qual é a rima e o ritmo do texto","o quê, quem, quando, onde, como e por quê"], a:3, exp:"Essas seis perguntas garantem que o leitor receba as informações essenciais logo no primeiro parágrafo da notícia." },
    { t:"apl", q:"O fato: a escola estadual Monte Alto venceu a feira de ciências do estado com um projeto de filtro de água de baixo custo. Qual manchete informa o fato com objetividade, sem opinião?", opts:["Finalmente uma escola pública faz algo que presta","Escola estadual vence feira de ciências com filtro de água de baixo custo","Projeto genial humilha concorrentes na feira de ciências","Filtro barato demais para ser levado a sério vence feira"], a:1, exp:"As outras manchetes carregam juízos de valor («finalmente... que presta», «genial», «humilha», «barato demais»). A manchete correta só informa o fato." },
    { t:"apl", q:"Leia o trecho de uma reportagem: «A usina solar foi inaugurada na terça-feira. Ela vai abastecer 40 mil casas. Segundo a empresa, essa é a maior do interior do estado.» Os termos «Ela» e «essa» retomam, respectivamente:", opts:["a terça-feira e a empresa","as casas e a empresa","a usina solar e a usina solar","a inauguração e as casas"], a:2, exp:"Os dois termos retomam o mesmo referente por caminhos diferentes: «ela» é pronome pessoal e «essa», demonstrativo. Coesão por retomada mantém o texto coeso sem repetição." },
    { t:"des", q:"Como diretor, você recebeu este parágrafo para a página de NOTÍCIAS: «O novo terminal de ônibus abriu ontem com 20 plataformas. A obra, felizmente muito bonita, custou R$ 8 milhões e deve atender 15 mil passageiros por dia.» Para publicá-lo como notícia, você deve:", opts:["retirar «felizmente muito bonita», juízo de valor do repórter, e manter os dados verificáveis","acrescentar mais adjetivos elogiosos ao texto","manter o texto como está, pois notícia também é opinião","transformar a frase em manchete sem mudar nada"], a:0, exp:"«Felizmente muito bonita» é avaliação pessoal que contaminou a notícia. Números, datas e capacidade são verificáveis e podem ficar." },
    { t:"des", q:"Um estagiário escreveu: «O incêndio atingiu o mercado municipal na madrugada de domingo. Ninguém se feriu. As chamas destruíram 30 boxes. O mercado foi fundado em 1920, época em que a cidade vivia do comércio de café. A causa, segundo os bombeiros, foi um curto-circuito.» Seguindo a pirâmide invertida, qual ajuste melhora a notícia?", opts:["começar o texto pela fundação do mercado em 1920","cortar a informação sobre a causa do incêndio","antecipar a causa do incêndio para perto do início e deixar o histórico de 1920 para o final","substituir «ninguém se feriu» por um elogio aos bombeiros"], a:2, exp:"A causa do incêndio é informação essencial e estava no fim; o histórico de 1920 é complementar e estava no meio. Inverter os dois corrige a hierarquia da notícia." }
  ] },
  "por-4": { q: [
    { t:"fix", q:"Na oração «Os estudantes do 9º ano apresentaram o projeto», o sujeito é:", opts:["o projeto","os estudantes do 9º ano","apresentaram","do 9º ano"], a:1, exp:"O sujeito é o termo com o qual o verbo concorda («apresentaram» — eles apresentaram) e sobre o qual se declara algo. Seu núcleo é «estudantes»." },
    { t:"fix", q:"Em «O técnico entregou o relatório à diretora», os termos «o relatório» e «à diretora» funcionam, respectivamente, como:", opts:["sujeito e predicado","adjunto adverbial e sujeito","objeto direto e objeto indireto","aposto e vocativo"], a:2, exp:"«O relatório» completa o verbo sem preposição (objeto direto); «à diretora» liga-se ao verbo por preposição (objeto indireto). Quem entrega, entrega algo a alguém." },
    { t:"apl", q:"Numa reportagem, lê-se: «Na madrugada de domingo, os bombeiros resgataram três pessoas do prédio em chamas.» Sintaticamente, a expressão «Na madrugada de domingo» é:", opts:["sujeito da oração","objeto direto","predicativo do sujeito","adjunto adverbial de tempo"], a:3, exp:"A expressão indica quando ocorreu a ação: circunstância de tempo. O sujeito é «os bombeiros», e o objeto direto, «três pessoas»." },
    { t:"apl", q:"No bilhete «Marina, devolva meu caderno amanhã», a palavra «Marina» exerce a função de:", opts:["vocativo — termo usado para chamar o interlocutor","sujeito do verbo «devolva»","objeto direto do verbo","adjunto adverbial de lugar"], a:0, exp:"O sujeito de «devolva» é «você», implícito no imperativo. «Marina» apenas nomeia a pessoa chamada, sem participar da estrutura da oração." },
    { t:"des", q:"Compare: «Bateram à porta durante a aula.» e «Choveu muito ontem.» Sobre os sujeitos dessas orações, é correto dizer:", opts:["ambas têm sujeito simples e explícito","a primeira tem sujeito oculto e a segunda, sujeito composto","ambas têm sujeito indeterminado","na primeira, o sujeito é indeterminado (verbo na 3ª pessoa do plural, sem referente); na segunda, não há sujeito, pois «chover» indica fenômeno da natureza"], a:3, exp:"Dois casos diferentes: verbo no plural sem sujeito identificável = sujeito indeterminado; verbo de fenômeno natural = oração sem sujeito. Confundi-los é o erro mais comum." }
  ] },
  "por-5": { q: [
    { t:"fix", q:"Uma oração subordinada é aquela que:", opts:["sempre aparece no início do período","não contém nenhum verbo","depende sintaticamente de outra oração, exercendo nela uma função (como sujeito, adjunto ou complemento)","expressa sempre a informação principal do período"], a:2, exp:"A oração subordinada não tem sentido completo sozinha no período: ela exerce uma função dentro da oração principal, como em «Espero que você venha»." },
    { t:"fix", q:"Quanto à função que exercem, as orações subordinadas classificam-se em:", opts:["substantivas, adjetivas e adverbiais","simples e compostas","ativas e passivas","diretas e indiretas"], a:0, exp:"Subordinadas substantivas funcionam como substantivo («Desejo que vençam»), adjetivas, como adjetivo («alunos que estudam»), e adverbiais, como advérbio («Quando chove, falto»)." },
    { t:"apl", q:"Na frase «Embora chovesse muito, o show aconteceu», a oração «Embora chovesse muito» é subordinada adverbial:", opts:["causal — indica a causa do show","concessiva — apresenta um obstáculo que não impediu a ação principal","condicional — impõe uma condição para o show","final — indica o objetivo do show"], a:1, exp:"A concessiva admite um contraste: apesar da chuva, o show aconteceu. Conjunções como «embora», «apesar de» e «mesmo que» introduzem esse valor." },
    { t:"apl", q:"Em «É provável que a prova seja adiada», a oração «que a prova seja adiada» é subordinada substantiva:", opts:["objetiva direta","predicativa","apositiva","subjetiva — funciona como sujeito de «é provável»"], a:3, exp:"Não há sujeito fora da oração: o que «é provável»? Que a prova seja adiada. A própria oração exerce a função de sujeito, por isso é subjetiva." },
    { t:"des", q:"No período «Quando o ônibus quebrou, os passageiros reclamaram que já estavam atrasados», há duas orações subordinadas. Elas são:", opts:["uma adverbial temporal («Quando o ônibus quebrou») e uma substantiva objetiva direta («que já estavam atrasados», complemento de «reclamaram»)","duas adjetivas restritivas","uma causal e uma consecutiva","duas coordenadas adversativas"], a:0, exp:"São dois passos: «quando» indica tempo (adverbial temporal); reclamar algo = verbo transitivo direto, e a oração introduzida por «que» é seu complemento (objetiva direta)." }
  ] },
  "por-6": { q: [
    { t:"fix", q:"Os dois-pontos são usados, entre outras funções, para:", opts:["separar o sujeito do predicado","indicar dúvida do autor","substituir qualquer vírgula do texto","introduzir uma explicação, uma citação ou uma enumeração"], a:3, exp:"Os dois-pontos anunciam o que vem a seguir: «Ele repetiu o aviso: saiam já!» Nunca se coloca vírgula ou dois-pontos entre sujeito e verbo." },
    { t:"fix", q:"Qual frase usa a vírgula corretamente para isolar um adjunto adverbial deslocado?", opts:["Os alunos, terminaram a prova cedo.","Depois do sinal, os alunos voltaram para a sala.","Comprei, lápis, caneta e borracha.","O caderno da, Marina sumiu."], a:1, exp:"Só a segunda frase isola corretamente o adjunto adverbial antecipado. As outras cometem o erro clássico de separar sujeito do verbo ou o verbo do seu complemento." },
    { t:"apl", q:"Numa entrevista, o jornalista transcreveu as palavras exatas da cientista, na primeira pessoa. Para sinalizar ao leitor que aquelas palavras são dela, o recurso de pontuação adequado é:", opts:["as aspas","o ponto e vírgula","o apóstrofo","o asterisco"], a:0, exp:"As aspas marcam o discurso direto, isto é, a citação literal da fala de alguém. O travessão também pode cumprir esse papel em diálogos de narrativas." },
    { t:"apl", q:"No anúncio «Promoção imperdível: pague 1, leve 2!», os dois-pontos e o ponto de exclamação têm, respectivamente, as funções de:", opts:["separar sujeito e verbo / indicar pergunta","marcar citação / indicar pausa longa","anunciar a explicação da promoção / reforçar o entusiasmo e chamar a atenção do leitor","indicar dúvida / encerrar uma enumeração"], a:2, exp:"Os dois-pontos introduzem o detalhamento da oferta, e a exclamação dá tom de empolgação — escolhas de pontuação pensadas para convencer o consumidor." },
    { t:"des", q:"Leia com atenção: I. «Os jogadores, que estavam cansados, perderam a final.» II. «Os jogadores que estavam cansados perderam a final.» A presença ou a ausência das vírgulas muda o sentido porque:", opts:["não muda nada: as frases são idênticas em sentido","em I, as vírgulas generalizam (TODOS os jogadores estavam cansados — explicativa); em II, sem vírgulas, apenas ALGUNS, os cansados, perderam — restritiva","em I, a frase fica gramaticalmente incorreta","em II, a frase se transforma em pergunta"], a:1, exp:"As vírgulas transformam a oração adjetiva restritiva em explicativa. No 8º/9º ano, esse é o efeito de sentido de pontuação mais cobrado: restringe ou generaliza o referente." }
  ] },
  "por-7": { q: [
    { t:"fix", q:"Em «O repórter entrevistou os moradores da rua alagada», o objeto direto é:", opts:["os moradores","o repórter","da rua alagada","entrevistou"], a:0, exp:"Quem entrevista, entrevista alguém: «os moradores» completa o verbo sem preposição. «O repórter» é o sujeito, e «da rua alagada» especifica quais moradores." },
    { t:"apl", q:"Na carta de um leitor ao jornal: «Como o prefeito não respondeu, escrevo para cobrar uma solução.» A oração «Como o prefeito não respondeu» expressa:", opts:["comparação","finalidade","consequência","causa"], a:3, exp:"No início do período, «como» tem valor de «já que»: apresenta a causa da carta. A falta de resposta é o motivo, não a consequência da cobrança." },
    { t:"apl", q:"Um aluno escreveu: «Preciso que você compre: caderno caneta e régua.» A pontuação correta para a enumeração é:", opts:["caderno. caneta. e régua","caderno; caneta; e régua","caderno, caneta e régua","caderno: caneta: régua"], a:2, exp:"Vírgulas separam os itens de uma enumeração, e o «e» entra antes do último item. Ponto final cortaria o período, e repetir dois-pontos não tem função." },
    { t:"des", q:"Analise o período: «Os professores, que aderiram à greve, não deram aula ontem.» Sobre ele, é correto afirmar:", opts:["a oração entre vírgulas é restritiva: só alguns professores aderiram à greve","a oração entre vírgulas é adjetiva explicativa (generaliza: todos os professores aderiram), e «ontem» é adjunto adverbial de tempo","«que aderiram à greve» é o sujeito de «não deram»","as vírgulas são proibidas nesse período"], a:1, exp:"Dois passos: classificar a subordinada pelas vírgulas (explicativa) e reconhecer a circunstância de tempo. O sujeito continua sendo «os professores»." },
    { t:"des", q:"Um redator escreveu: «Fazem dez anos que o bairro não tem posto de saúde. Os moradores, que esperam desde então, já protocolaram três abaixo-assinados.» Sobre o texto, assinale a análise correta:", opts:["o verbo «fazer» indica tempo decorrido e deve ficar no singular («Faz dez anos»); «que esperam desde então» é oração subordinada adjetiva explicativa","«Fazem» está correto porque concorda com «anos»","«que esperam desde então» é oração coordenada sindética","o sujeito de «Fazem» é «dez anos»"], a:0, exp:"Dois conhecimentos em jogo: o «fazer» de tempo decorrido é impessoal (não tem sujeito, fica no singular), e a oração entre vírgulas explica, não restringe, «os moradores»." }
  ] },
  "por-8": { q: [
    { t:"fix", q:"Quando a história é contada em primeira pessoa por alguém que participa dos fatos («Eu corri para o portão...»), temos um narrador:", opts:["onisciente","observador","personagem","editorial"], a:2, exp:"O narrador personagem conta a própria história em 1ª pessoa: ele é ao mesmo tempo quem narra e quem vive os acontecimentos." },
    { t:"fix", q:"O narrador onisciente é aquele que:", opts:["participa da história como protagonista","conhece tudo sobre os personagens, inclusive pensamentos e sentimentos, sem participar da trama","registra apenas o que uma câmera filmaria","nunca revela o desfecho da história"], a:1, exp:"Onisciente = «que tudo sabe». Ele narra em 3ª pessoa e tem acesso total à mente dos personagens, como um observador invisível e todo-poderoso." },
    { t:"apl", q:"Leia: «Beto entrou no tribunal suando frio. Pensava na promessa que fizera ao pai e torcia para que ninguém percebesse seu medo. Do outro lado da sala, dona Zilda desconfiava que o rapaz escondia algo.» O narrador desse trecho é:", opts:["personagem, pois conta o que viu","observador, pois narra só o que uma câmera registraria","a própria dona Zilda","onisciente, pois narra em 3ª pessoa e revela os pensamentos de dois personagens diferentes"], a:3, exp:"O narrador entra na cabeça de Beto (a promessa, o medo) e na de dona Zilda (a desconfiança). Acesso a pensamentos de vários personagens = onisciência." },
    { t:"apl", q:"Leia: «Eu não sabia o que havia do outro lado do muro. Só ouvia o barulho das máquinas e imaginava.» A escolha do narrador em 1ª pessoa limita o leitor porque:", opts:["só sabemos o que o narrador personagem sabe — o mistério do outro lado do muro se mantém para nós também","o texto fica gramaticalmente incorreto","passamos a conhecer os pensamentos de todos os personagens","a história deixa de ter enredo"], a:0, exp:"O ponto de vista em 1ª pessoa restringe a informação ao que o narrador vê e sabe. Essa limitação é um recurso: cria suspense e aproxima o leitor do personagem." },
    { t:"des", q:"Leia dois textos sobre o mesmo assalto: I. «Eu vi o carro parar e o homem sair correndo. Não sei o que ele levou.» II. «O homem saiu do carro certo de que ninguém o reconheceria. Estava enganado: a dona da loja memorizava cada detalhe.» Comparando-os, conclui-se que:", opts:["ambos têm narrador personagem","ambos têm narrador onisciente","em I, o narrador personagem sabe apenas o que viu; em II, o narrador onisciente conhece até a intenção do ladrão e o pensamento da dona da loja","em II, o narrador não conhece o pensamento de ninguém"], a:2, exp:"A comparação exige dois passos: reconhecer a limitação da 1ª pessoa em I e o acesso total à mente dos personagens em II — dois efeitos narrativos opostos." }
  ] },
  "por-9": { q: [
    { t:"fix", q:"A diferença entre denotação e conotação é que:", opts:["denotação é o sentido figurado; conotação, o sentido de dicionário","denotação é o sentido literal, de dicionário; conotação é o sentido figurado, criado pelo contexto","as duas significam exatamente a mesma coisa","denotação só existe em poemas"], a:1, exp:"«Ele comprou um cachorro» é denotativo (o animal). «Aquele juiz é um cachorro» é conotativo: o contexto cria um sentido figurado, nada literal." },
    { t:"fix", q:"Na frase «Aquele menino é uma flecha», há uma metáfora. A diferença entre metáfora e comparação é que:", opts:["a metáfora aproxima os termos sem conectivo comparativo; a comparação usa conectivos como «como» ou «tal qual» («rápido como uma flecha»)","a metáfora só pode aparecer em versos","a comparação nunca usa conectivos","não há diferença alguma entre elas"], a:0, exp:"Ambas aproximam elementos diferentes; o que muda é a presença do conectivo. Com «como», é comparação explícita; sem ele, metáfora." },
    { t:"apl", q:"Num anúncio de plano de saúde, lê-se: «Nós cuidamos de você em cada momento da sua vida.» No verso de uma canção, lê-se: «Seu abraço é o meu abrigo.» O verso da canção, diferentemente do anúncio, usa linguagem:", opts:["técnica","denotativa","conotativa — «abrigo» aparece em sentido figurado para sugerir proteção e acolhimento","burocrática"], a:2, exp:"Ninguém mora dentro de um abraço: «abrigo» ganha sentido figurado de proteção. O anúncio, por sua vez, usa as palavras no sentido literal." },
    { t:"apl", q:"Na mensagem «Mãe, eu já te liguei umas mil vezes!», a expressão «umas mil vezes» é:", opts:["uma metáfora","um eufemismo","uma comparação","uma hipérbole — exagero intencional que enfatiza a insistência de quem ligou"], a:3, exp:"Ninguém liga mil vezes seguidas: o exagero da hipérbole dramatiza a situação e aproxima a fala da linguagem do dia a dia." },
    { t:"des", q:"Leia o verso: «O vento chorou na janela a noite inteira, e a casa, velha e cansada, suspirou.» Nele, identificam-se:", opts:["apenas comparações marcadas pelo conectivo «como»","ironia e antítese","personificação (prosopopeia), pois elementos da natureza e da casa recebem ações e estados humanos («chorou», «suspirou», «cansada»), e linguagem conotativa","sentido literal e vocabulario técnico"], a:2, exp:"Dois passos: perceber que vento e casa agem como pessoas (personificação em dois pontos do verso) e que todo o verso funciona em sentido figurado." }
  ] },
  "por-10": { q: [
    { t:"fix", q:"A Semana de Arte Moderna, marco inicial do Modernismo brasileiro, aconteceu:", opts:["em 1922, no Theatro Municipal de São Paulo, no ano do centenário da Independência","em 1888, com a assinatura da Lei Áurea","em 1500, com a chegada dos portugueses","em 1964, durante a ditadura militar"], a:0, exp:"Em fevereiro de 1922, artistas como Mário de Andrade, Oswald de Andrade, Tarsila do Amaral e Villa-Lobos apresentaram ao público uma arte de ruptura com o passado." },
    { t:"fix", q:"Qual alternativa reúne características do Modernismo brasileiro?", opts:["rima rica, métrica rigorosa e temas religiosos","linguagem rebuscada e imitação dos modelos europeus","versos livres, linguagem próxima da fala, valorização do cotidiano e da cultura brasileira e ruptura com as regras do passado","textos escritos exclusivamente em latim"], a:2, exp:"Os modernistas quebraram com o formalismo: verso livre, fala do povo, temas do Brasil real e humor crítico — o oposto da linguagem empolada dos séculos anteriores." },
    { t:"apl", q:"Leia a quadra de um poema fictício: «Minha terra tem telas de celular / Tem engarrafamento, tem cafezinho / Tem gente que fala 'véi' e 'mano' / E eu gosto dela assim mesmo.» Qual traço modernista o poema apresenta?", opts:["métrica rigorosa e rimas perfeitas","vocabulário erudito e latino","tema da mitologia grega","linguagem coloquial e tema do cotidiano brasileiro, em verso livre"], a:3, exp:"Gírias, cena urbana e ausência de rima obrigatória são exatamente as marcas que o Modernismo defendeu desde 1922: arte brasileira falando como o brasileiro fala." },
    { t:"apl", q:"O Modernismo surgiu num Brasil que vivia a industrialização de São Paulo, o fim da Primeira Guerra Mundial e o centenário da Independência. Esse contexto ajuda a explicar por que os modernistas:", opts:["queriam copiar a literatura do período colonial","buscavam romper com o passado e criar uma arte nova, com a cara do Brasil moderno que nascia","eram contra qualquer mudança nas artes","escreviam apenas sobre a corte portuguesa"], a:1, exp:"Um país que se industrializava e comemorava 100 anos de independência cobrava uma identidade própria. A arte modernista foi a resposta: renovação e brasilidade." },
    { t:"des", q:"No Manifesto Antropófago (1928), Oswald de Andrade propôs que o Brasil «devorasse» as culturas estrangeiras e as transformasse em algo próprio. Combinando essa ideia com as características do Modernismo, um artista antropofágico faria:", opts:["cópias fiéis de obras europeias","arte sem nenhuma influência externa","arte apenas com temas indígenas, recusando tudo o que é moderno","arte que mistura técnicas e referências estrangeiras a temas e à linguagem brasileiros, criando algo original"], a:3, exp:"Dois passos: entender a metáfora de «devorar» (absorver e transformar, não copiar nem rejeitar) e aplicá-la à criação artística brasileira." }
  ] },
  "por-11": { q: [
    { t:"fix", q:"Você é o curador de um museu de literatura. Num manuscrito, lê-se: «Saí de casa cedo. Mal sabia eu o que o destino me preparava.» O narrador desse trecho é:", opts:["onisciente","observador","inexistente","personagem — conta a própria história em 1ª pessoa"], a:3, exp:"O «eu» que narra é o mesmo que vive os fatos. A pista «mal sabia eu» mostra ainda a limitação típica do narrador personagem: ele não conhece o futuro." },
    { t:"apl", q:"No cartaz de um quadro, o curador escreveu: «A cidade da tela é um formigueiro de gente.» A expressão destacada é:", opts:["linguagem denotativa, com sentido de dicionário","uma comparação marcada pelo conectivo «como»","uma metáfora — aproxima cidade e formigueiro sem conectivo, em sentido figurado","uma hipérbole — puro exagero numérico"], a:2, exp:"A cidade não é literalmente um formigueiro: a aproximação sem «como» caracteriza a metáfora e sugere movimento incessante de multidão." },
    { t:"apl", q:"O museu recebeu um poema de 1925 escrito em versos livres, sem rimas, com linguagem de conversa e cenas do cotidiano paulistano. Sua classificação mais provável é:", opts:["poema modernista","poema trovadoresco medieval","romance barroco","carta pessoal sem valor literário"], a:0, exp:"Data (pós-1922), verso livre, linguagem coloquial e tema urbano brasileiro: o conjunto aponta para o Modernismo, mesmo sem saber quem é o autor." },
    { t:"des", q:"Compare dois textos sobre a mesma praça: I. «A praça ostenta, sob o pálido luar, flores que exalam etéreos aromas.» (1900) II. «A praça tem banco quebrado, pombos, gente apressada e o melhor pastel da cidade.» (1926) Sobre eles, é correto afirmar:", opts:["I é modernista e II é parnasiano","I tem linguagem rebuscada e idealizada, típica do que o Modernismo combateu; II tem linguagem coloquial e tema cotidiano, marcas modernistas","os dois textos têm exatamente o mesmo estilo","II não pode ser literatura por ser simples demais"], a:1, exp:"A comparação exige reconhecer os dois estilos: a praça idealizada e empolada de 1900 contra a praça real e falada de 1926 — a virada modernista em cena." },
    { t:"des", q:"Leia o texto que o museu vai expor: «Eu era só um menino quando o rádio chegou ao bairro. A vizinhança inteira se espremia na sala do seu Chico. Aquela caixa falante parecia mágica — e, de certo modo, era.» Nesse texto, identificam-se:", opts:["narrador onisciente e linguagem denotativa","narrador personagem (1ª pessoa) e conotação — «caixa falante» e «mágica» em sentido figurado","narrador observador e comparação marcada por «como»","texto jornalístico e objetivo"], a:1, exp:"Dois passos: o «eu» que conta a própria memória é narrador personagem, e o rádio chamado de «caixa falante» e «mágica» mostra a linguagem em sentido figurado." }
  ] }
});
