/* Banco de questões — Ciências (7º ano) — gerado para o protótipo Trilha do Saber */
window.QUESTOES = window.QUESTOES || {};
Object.assign(window.QUESTOES, {
  "cie-0": { q: [
    { t:"fix", q:"Em uma cadeia alimentar, os organismos chamados de produtores são aqueles que:", opts:["produzem o próprio alimento, como as plantas e as algas, por meio da fotossíntese","se alimentam de plantas, como os herbívoros","caçam outros animais para se alimentar","decompõem restos de organismos mortos"], a:0, exp:"Produtores, como plantas e algas, fabricam o próprio alimento pela fotossíntese. Eles são a base de toda cadeia alimentar." },
    { t:"fix", q:"O consumidor primário de uma cadeia alimentar é o organismo que:", opts:["se alimenta de outros animais carnívoros","produz o próprio alimento","se alimenta diretamente dos produtores, como fazem os herbívoros","decompõe a matéria orgânica morta"], a:2, exp:"Consumidores primários são os herbívoros: comem os produtores. Os carnívoros que os caçam são os consumidores secundários." },
    { t:"apl", q:"Na horta da escola, Marina observou que o capim é comido pelo gafanhoto, que é comido pelo sapo, que é comido pela cobra. Nessa cadeia alimentar, o gafanhoto é:", opts:["produtor","consumidor primário","consumidor secundário","decompositor"], a:1, exp:"O gafanhoto come o capim (produtor), então é herbívoro: consumidor primário. O sapo, que o come, é o consumidor secundário." },
    { t:"apl", q:"Depois que uma chuva de folhas cobriu o jardim, fungos e bactérias começaram a agir sobre elas. O papel desses organismos na natureza é:", opts:["produzir oxigênio para os animais respirarem","caçar pequenos insetos do solo","servir de alimento apenas para as plantas","decompor a matéria orgânica morta, devolvendo nutrientes ao solo"], a:3, exp:"Fungos e bactérias são decompositores: quebram restos de organismos e devolvem nutrientes ao solo, fechando o ciclo da matéria." },
    { t:"des", q:"Em um manguezal, a cadeia alimentar é: fitoplâncton → camarão → peixe pequeno → garça. Se uma doença eliminar quase todos os peixes pequenos, o efeito mais provável, depois de algum tempo, será:", opts:["o aumento do fitoplâncton, pois haverá menos camarões para comê-lo","o aumento da população de garças, pois sobrará espaço no manguezal","a diminuição das garças, pela falta de alimento, e o aumento dos camarões, sem o seu predador","a extinção imediata de todos os organismos do manguezal"], a:2, exp:"Sem os peixes, as garças perdem sua fonte de alimento e diminuem; já os camarões, livres do predador, aumentam — e comem mais fitoplâncton. Toda mudança num elo da cadeia afeta os demais." }
  ] },
  "cie-1": { q: [
    { t:"fix", q:"A relação ecológica em que as duas espécies envolvidas são beneficiadas, como ocorre entre a abelha e a flor, é chamada de:", opts:["predação","competição","parasitismo","mutualismo"], a:3, exp:"No mutualismo, ambos ganham: a abelha coleta néctar e, em troca, ajuda a flor na polinização." },
    { t:"fix", q:"Quando um leão caça uma zebra para se alimentar, a relação ecológica entre eles é de:", opts:["predação","mutualismo","comensalismo","cooperação"], a:0, exp:"Na predação, um organismo (o predador) mata e se alimenta de outro (a presa)." },
    { t:"apl", q:"O carrapato vive preso à pele do cachorro, sugando seu sangue e enfraquecendo-o, sem trazer benefício algum ao cão. Essa relação ecológica é:", opts:["comensalismo","mutualismo","parasitismo","predação"], a:2, exp:"No parasitismo, um organismo (o parasita) se beneficia às custas do outro (o hospedeiro), prejudicando-o, geralmente sem matá-lo." },
    { t:"apl", q:"O pássaro anu pousa sobre o gado e se alimenta dos carrapatos que estão na pele dos bois; os bois, por sua vez, ficam livres desses parasitas. Essa relação é um exemplo de:", opts:["competição","mutualismo","parasitismo","predação"], a:1, exp:"Ambos se beneficiam: o anu ganha alimento e o boi se livra dos carrapatos. É um caso de mutualismo." },
    { t:"des", q:"Em um aquário, duas espécies de peixe se alimentam do mesmo tipo de ração e ocupam o mesmo espaço. Com o tempo, a população de uma delas diminuiu muito, sem que um peixe comesse o outro. A relação que explica esse resultado é a:", opts:["competição, pois as duas espécies disputam o mesmo recurso limitado","predação, pois uma espécie se alimentou da outra","mutualismo, pois as duas espécies se ajudavam","comensalismo, pois uma espécie se aproveitava da outra sem prejudicá-la"], a:0, exp:"Quando dois organismos disputam o mesmo recurso, como alimento e espaço, há competição, e uma das populações tende a diminuir. Não houve predação, pois nenhum peixe comeu o outro." }
  ] },
  "cie-2": { q: [
    { t:"fix", q:"O efeito estufa é intensificado principalmente pelo aumento, na atmosfera, de:", opts:["oxigênio liberado pelas florestas","gases como o dióxido de carbono, lançados pela queima de combustíveis fósseis","vapor de água vindo das chuvas","ozônio produzido pelos raios solares"], a:1, exp:"A queima de gasolina, carvão e outros combustíveis fósseis lança CO₂ e mais gases que retêm calor na atmosfera, intensificando o aquecimento global." },
    { t:"fix", q:"O desmatamento de uma floresta tem como consequência ambiental direta:", opts:["o aumento da quantidade de água potável no solo","o aumento do número de espécies na região","a melhoria da qualidade do ar local","a perda de habitat e a redução da biodiversidade"], a:3, exp:"Sem as árvores, os animais perdem abrigo e alimento, o solo fica exposto à erosão e muitas espécies desaparecem da região." },
    { t:"apl", q:"Uma fábrica despejou resíduos químicos em um rio. Dias depois, peixes apareceram mortos e a água ficou imprópria para consumo. A principal causa da morte dos peixes foi:", opts:["a contaminação da água por substâncias tóxicas, que envenenou os organismos e reduziu o oxigênio disponível","o aumento da quantidade de algas produtoras de oxigênio","a falta de luz solar causada pelas chuvas daqueles dias","a competição entre os peixes pelo alimento"], a:0, exp:"Resíduos químicos tóxicos contaminam a água, podendo matar os organismos diretamente ou esgotar o oxigênio dissolvido, o que sufoca peixes e outros animais." },
    { t:"apl", q:"Para reduzir a quantidade de plástico que vai parar nos oceanos, a atitude mais eficaz no dia a dia de uma escola seria:", opts:["enterrar o plástico no pátio, longe dos rios","queimar o plástico no fim das aulas","separar o plástico para reciclagem e evitar produtos descartáveis","jogar o plástico no ralo, pois ele vai para a estação de tratamento"], a:2, exp:"Reduzir o uso de descartáveis e destinar o plástico à reciclagem impede que ele chegue aos rios e mares. Enterrar polui o solo e queimar polui o ar." },
    { t:"des", q:"Após o desmatamento de uma encosta, as chuvas passaram a carregar o solo para o rio, que ficou barrento; os peixes diminuíram e a cidade vizinha começou a racionar água. Essa sequência mostra que:", opts:["os impactos ambientais ficam restritos ao local onde começam","apenas os animais terrestres sofrem com o desmatamento","o racionamento de água não tem relação com a floresta","um impacto ambiental desencadeia outros, em cadeia, afetando ecossistemas e pessoas"], a:3, exp:"O desmatamento expõe o solo; a erosão leva terra para o rio (assoreamento); os peixes diminuem e a água para consumo fica comprometida. Os impactos se acumulam em cadeia." }
  ] },
  "cie-3": { q: [
    { t:"fix", q:"Em um recife de corais, as algas fazem a fotossíntese, os peixes herbívoros comem as algas e os tubarões caçam esses peixes. Nessa cadeia alimentar, o tubarão é:", opts:["produtor","consumidor primário","consumidor secundário","decompositor"], a:2, exp:"O tubarão se alimenta do peixe herbívoro (consumidor primário), portanto ocupa o nível de consumidor secundário." },
    { t:"apl", q:"O peixe-palhaço vive entre os tentáculos da anêmona, protegido de predadores e, em troca, afasta os peixes que se alimentariam dela. Essa relação ecológica é:", opts:["mutualismo","parasitismo","competição","predação"], a:0, exp:"Os dois se beneficiam — proteção para o peixe e defesa para a anêmona. É um mutualismo clássico dos recifes." },
    { t:"apl", q:"O aquecimento da água do mar tem provocado o branqueamento dos corais: eles expulsam as algas que vivem em seus tecidos e que lhes fornecem alimento. Esse fenômeno mostra que:", opts:["os corais são decompositores e independem das algas","as mudanças ambientais podem romper relações ecológicas e ameaçar todo o recife","o branqueamento melhora a saúde dos corais","as algas são parasitas dos corais, e a saída delas os fortalece"], a:1, exp:"Corais e algas vivem em mutualismo; a água quente rompe essa parceria, os corais passam fome e todo o ecossistema do recife fica ameaçado." },
    { t:"des", q:"Num recife, a cadeia alimentar é: alga → peixe-papagaio → moreia → tubarão. A pesca excessiva retirou quase todos os tubarões da região. O resultado mais provável, depois de algum tempo, é:", opts:["o aumento das algas, já que haverá menos peixes-papagaio","a diminuição das moreias, por falta de alimento","o desaparecimento imediato de todos os peixes do recife","o aumento das moreias, sem o seu predador, e a diminuição dos peixes-papagaio, mais caçados"], a:3, exp:"Sem tubarões, as moreias se multiplicam e caçam mais peixes-papagaio; com menos herbívoros, as algas podem crescer demais e sufocar os corais. Retirar o predador do topo desequilibra toda a cadeia." },
    { t:"des", q:"Duas turmas fizeram experimentos em dois lagos parecidos. A Turma A retirou os fungos e as bactérias do sedimento de um lago; a Turma B dobrou a quantidade de peixes herbívoros no outro. Após algumas semanas, no lago A os restos orgânicos se acumularam e os nutrientes sumiram da água; no lago B, as plantas aquáticas quase desapareceram. Esses resultados mostram, respectivamente, a importância:", opts:["dos produtores e dos predadores de topo","dos decompositores na reciclagem de nutrientes e do equilíbrio entre os níveis da cadeia alimentar","dos parasitas e da competição entre espécies","da poluição e do desmatamento nas margens"], a:1, exp:"Sem decompositores, a matéria orgânica não volta a ser nutriente para as plantas; e herbívoros em excesso consomem os produtores mais rápido do que eles se recuperam. Cada papel ecológico importa." }
  ] },
  "cie-4": { q: [
    { t:"fix", q:"No estado sólido, as partículas de um material estão:", opts:["muito afastadas e se movendo livremente","bem próximas e organizadas, apenas vibrando, o que dá forma e volume definidos ao sólido","próximas, mas deslizando umas sobre as outras","totalmente paradas, sem nenhum movimento"], a:1, exp:"No sólido, as partículas ficam juntas e organizadas, vibrando no lugar — por isso o sólido tem forma e volume próprios." },
    { t:"fix", q:"A passagem do estado líquido para o gasoso, como acontece com a água fervendo na chaleira, é chamada de:", opts:["fusão","condensação","vaporização","solidificação"], a:2, exp:"Vaporização é a mudança de líquido para gasoso. Fusão é sólido → líquido; condensação, gasoso → líquido; solidificação, líquido → sólido." },
    { t:"apl", q:"Ao tirar uma garrafa gelada de suco da geladeira, a parte de fora fica molhada depois de alguns minutos. Isso acontece porque:", opts:["o suco atravessa o vidro da garrafa","a garrafa sua água de dentro para fora","o frio transforma o ar em água por fusão","o vapor de água do ar se condensa ao encostar na superfície fria"], a:3, exp:"O vapor de água presente no ar perde calor ao tocar a garrafa gelada e passa para o estado líquido: é a condensação. A água vem do ar, não de dentro da garrafa." },
    { t:"apl", q:"Uma pedra de gelo deixada no copo derrete aos poucos. A mudança de estado físico que ocorre com a água nesse caso é a:", opts:["fusão","vaporização","sublimação","condensação"], a:0, exp:"A passagem de sólido (gelo) para líquido, pelo ganho de calor, é chamada de fusão." },
    { t:"des", q:"Uma professora colocou naftalina em um armário fechado. Meses depois, a naftalina havia diminuído sem deixar nenhum líquido, e o armário estava com cheiro forte. O fenômeno que explica isso é:", opts:["a fusão, pois a naftalina derreteu e o líquido evaporou","a condensação, pois o ar úmido dissolveu a naftalina","a sublimação, pois ela passou diretamente do estado sólido para o gasoso","a solidificação, pois a naftalina se espalhou pelo armário"], a:2, exp:"A naftalina sublima: vai direto do estado sólido para o gasoso, sem passar pelo líquido. Por isso diminui sem molhar nada e ainda espalha cheiro pelo ar." }
  ] },
  "cie-5": { q: [
    { t:"fix", q:"Para separar o café passado do pó de café, o método de separação adequado é a:", opts:["filtração","decantação","evaporação","destilação"], a:0, exp:"O filtro de papel retém o sólido (o pó) e deixa o líquido passar: é a filtração." },
    { t:"fix", q:"Água e óleo, que não se misturam, formam uma mistura:", opts:["homogênea, pois os dois são líquidos","heterogênea, pois é possível ver duas fases distintas","homogênea, pois os dois são transparentes","heterogênea, pois os dois têm cores iguais"], a:1, exp:"Como dá para enxergar duas camadas (duas fases), a mistura é heterogênea. O óleo, menos denso, fica por cima." },
    { t:"apl", q:"Na cozinha, Lucas deixou cair sal em um copo com água e mexeu até dissolver tudo. Para recuperar o sal, ele deve:", opts:["coar a mistura em uma peneira","usar um funil com filtro de papel","aquecer a mistura até a água evaporar","deixar a mistura parada até o sal decantar"], a:2, exp:"O sal dissolvido não é retido por peneira ou filtro e não decanta. Evaporando a água, o sal fica no recipiente." },
    { t:"apl", q:"Uma mistura de areia com limalha de ferro pode ser separada com rapidez usando:", opts:["um funil de decantação","uma peneira comum","um filtro de café","um ímã, que atrai o ferro e deixa a areia"], a:3, exp:"A separação magnética aproveita a atração do ímã sobre o ferro — um método rápido para esse tipo de mistura de sólidos." },
    { t:"des", q:"Uma equipe precisa separar uma mistura de água, sal e areia, recuperando os três componentes. A sequência correta de procedimentos é:", opts:["filtrar para reter a areia e, depois, destilar a água salgada, obtendo a água pura e o sal","destilar tudo primeiro e, depois, filtrar a areia","peneirar a mistura e, depois, usar um ímã no sal","decantar o sal, filtrar a areia e evaporar a água"], a:0, exp:"Primeiro a filtração separa o sólido não dissolvido (areia); depois a destilação evapora e condensa a água, deixando o sal. Peneira e ímã não funcionam aqui, e o sal dissolvido não decanta." }
  ] },
  "cie-6": { q: [
    { t:"fix", q:"Toda a matéria é formada por pequenas unidades chamadas átomos. No modelo atual, o átomo é composto basicamente de:", opts:["células e tecidos","apenas um núcleo, sem outras partes","pedaços de terra, água, ar e fogo","prótons e nêutrons no núcleo, com elétrons ao redor"], a:3, exp:"O átomo tem um núcleo com prótons (carga positiva) e nêutrons (sem carga), cercado por elétrons (carga negativa) na eletrosfera." },
    { t:"fix", q:"Uma molécula de água (H₂O) é formada por:", opts:["dois átomos de oxigênio e um de hidrogênio","dois átomos de hidrogênio e um de oxigênio","um átomo de hidrogênio e dois de oxigênio","um átomo de hidrogênio e um de oxigênio"], a:1, exp:"A fórmula H₂O indica 2 átomos de hidrogênio (o número 2 abaixo do H) ligados a 1 átomo de oxigênio." },
    { t:"apl", q:"O gás que inspiramos (O₂) e o gás carbônico que soltamos na respiração (CO₂) são substâncias diferentes porque:", opts:["suas moléculas têm tipos e quantidades diferentes de átomos","o O₂ é líquido e o CO₂ é gasoso","o CO₂ não contém oxigênio","o O₂ é formado por três átomos"], a:0, exp:"O₂ tem 2 átomos de oxigênio; CO₂ tem 1 átomo de carbono e 2 de oxigênio. Fórmulas diferentes significam substâncias com propriedades diferentes." },
    { t:"apl", q:"Na aula de Ciências, a professora explicou que um elemento químico é o conjunto de átomos que têm o mesmo número de:", opts:["nêutrons","moléculas","prótons","ligações"], a:2, exp:"O número de prótons (número atômico) é o que identifica um elemento: todo átomo com 8 prótons é oxigênio, por exemplo." },
    { t:"des", q:"Observe as fórmulas: O₂ (gás oxigênio) e O₃ (gás ozônio). Ambas contêm apenas átomos de oxigênio, mas são substâncias com propriedades muito diferentes. Isso acontece porque:", opts:["o ozônio contém carbono escondido na fórmula","o número de átomos em cada molécula é diferente, o que muda as propriedades da substância","o O₃ é uma mistura de O₂ com ar","os átomos de oxigênio do ozônio têm mais prótons"], a:1, exp:"Átomos do mesmo elemento são iguais entre si; o que muda é a quantidade deles em cada molécula (2 ou 3). Essa diferença na estrutura altera completamente as propriedades da substância." }
  ] },
  "cie-7": { q: [
    { t:"fix", q:"Quando a água passa do estado líquido para o sólido dentro do congelador, a mudança de estado é chamada de:", opts:["fusão","vaporização","solidificação","sublimação"], a:2, exp:"Líquido → sólido é solidificação. Fusão é o caminho contrário: sólido → líquido." },
    { t:"apl", q:"Uma cozinheira coou o caldo para retirar os pedaços de legumes e, em seguida, quis tirar o excesso de sal dissolvido, recuperando água sem sal. Para isso, ela deveria usar:", opts:["uma nova filtração, com filtro mais fino","decantação, deixando o sal descer ao fundo","um ímã, para atrair os grãos de sal","destilação, evaporando e condensando a água"], a:3, exp:"O sal dissolvido não pode ser filtrado nem decantado. Na destilação, a água evapora e condensa pura, enquanto o sal fica para trás." },
    { t:"apl", q:"Em um laboratório escolar, uma amostra de gás foi representada por bolinhas todas iguais, agrupadas de duas em duas. Essa amostra representa:", opts:["uma mistura de dois elementos","uma substância formada por moléculas com dois átomos do mesmo elemento, como o O₂","um composto de dois elementos diferentes, como o CO₂","átomos isolados, sem nenhuma ligação"], a:1, exp:"Bolinhas iguais em pares representam moléculas de um único elemento (como O₂ ou H₂). Se fossem bolinhas diferentes ligadas, seria um composto." },
    { t:"des", q:"Uma estudante afirmou: «Quando a água ferve e vira vapor, as moléculas de H₂O se quebram e viram átomos soltos de hidrogênio e oxigênio.» A correção correta para essa afirmação é:", opts:["na vaporização, as moléculas de H₂O permanecem iguais; o que muda é a distância e o movimento entre elas","a afirmação está certa, pois todo vapor é feito de átomos soltos","as moléculas de água se transformam em moléculas de O₂","o vapor de água é formado apenas por hidrogênio"], a:0, exp:"Mudanças de estado são transformações físicas: a molécula H₂O continua H₂O, só muda o estado. A quebra da molécula seria uma transformação química, outro tipo de fenômeno." },
    { t:"des", q:"Uma equipe recebeu uma mistura de areia, sal, água e pedacinhos de ferro e precisa separar os quatro componentes. A sequência mais eficiente é:", opts:["filtrar tudo, destilar e peneirar","destilar primeiro e filtrar depois","peneirar, filtrar e evaporar","usar um ímã para retirar o ferro, filtrar para reter a areia e evaporar (ou destilar) para separar a água do sal"], a:3, exp:"Cada método usa uma propriedade: o ímã retira o ferro, a filtração retém a areia (sólido não dissolvido) e a evaporação ou destilação separa a água do sal dissolvido." }
  ] },
  "cie-8": { q: [
    { t:"fix", q:"A digestão dos alimentos começa na boca, onde eles são:", opts:["mastigados pelos dentes e umedecidos pela saliva","absorvidos diretamente pelo sangue","transformados em fezes","armazenados por várias horas"], a:0, exp:"Na boca, os dentes trituram o alimento e a saliva o umedece, já iniciando a digestão do amido — é a primeira etapa da digestão." },
    { t:"fix", q:"No estômago, o alimento é misturado ao suco gástrico, que contém:", opts:["apenas água e sais minerais","bile produzida pelo pâncreas","ácido e enzimas que ajudam a digerir as proteínas","ar e fibras que amolecem o alimento"], a:2, exp:"O suco gástrico tem ácido clorídrico e enzimas, como a pepsina, que iniciam a digestão das proteínas no estômago." },
    { t:"apl", q:"Depois de um lanche, os nutrientes (vitaminas, glicose, aminoácidos) passam para o sangue principalmente no:", opts:["estômago","intestino delgado","esôfago","intestino grosso"], a:1, exp:"No intestino delgado, a digestão termina e suas vilosidades absorvem os nutrientes, que caem no sangue. O intestino grosso absorve principalmente água." },
    { t:"apl", q:"O médico explicou a Pedro que a bile, produzida pelo fígado e armazenada na vesícula biliar, ajuda a digestão porque:", opts:["destrói todas as bactérias do intestino","transforma proteínas em açúcares","absorve a água dos alimentos","quebra as gorduras em gotas menores, facilitando a ação das enzimas"], a:3, exp:"A bile não é uma enzima: ela separa a gordura em gotículas, facilitando o trabalho das enzimas digestivas no intestino." },
    { t:"des", q:"Uma pessoa com diarreia intensa fica desidratada principalmente porque:", opts:["o estômago para de produzir suco gástrico","o intestino grosso não consegue absorver a água, que é eliminada em excesso nas fezes","a saliva deixa de ser produzida pela boca","o fígado consome toda a água do corpo"], a:1, exp:"Uma das funções do intestino grosso é absorver água e sais. Na diarreia, essa absorção falha e a água sai nas fezes — por isso a reidratação é tão importante." }
  ] },
  "cie-9": { q: [
    { t:"fix", q:"O órgão que funciona como uma bomba, impulsionando o sangue para todo o corpo, é o:", opts:["pulmão","coração","fígado","rim"], a:1, exp:"O coração é um músculo que se contrai ritmicamente, bombeando o sangue pelos vasos para todo o corpo." },
    { t:"fix", q:"Nos pulmões, mais precisamente nos alvéolos, acontece:", opts:["a troca de gases: o oxigênio passa para o sangue e o gás carbônico sai do sangue","a digestão dos alimentos","a produção das células do sangue","a filtragem da urina"], a:0, exp:"Nos alvéolos pulmonares ocorrem as trocas gasosas: o O₂ entra no sangue e o CO₂ é eliminado para ser expirado." },
    { t:"apl", q:"Durante uma corrida, a respiração e os batimentos cardíacos de Ana aceleram. Isso acontece porque:", opts:["o corpo precisa economizar oxigênio","os pulmões precisam descansar mais rápido","o coração quer gastar menos energia","os músculos em atividade precisam de mais oxigênio e nutrientes, entregues mais rápido pelo sangue"], a:3, exp:"No exercício, os músculos consomem mais O₂ e produzem mais CO₂. Coração e pulmões aceleram juntos para atender a essa demanda." },
    { t:"apl", q:"Veias e artérias são vasos sanguíneos. A diferença básica entre elas é que:", opts:["as veias saem do coração e as artérias chegam a ele","as artérias transportam apenas sangue sem oxigênio","as artérias levam o sangue do coração para o corpo, e as veias trazem o sangue de volta ao coração","as veias têm paredes mais grossas que as artérias"], a:2, exp:"Artérias partem do coração, levando sangue ao corpo; veias retornam o sangue ao coração. Ter ou não oxigênio depende do trecho do circuito, não do tipo do vaso." },
    { t:"des", q:"O sangue que volta do corpo chega ao coração pobre em oxigênio e rico em gás carbônico. Para retornar ao corpo rico em oxigênio, ele precisa, obrigatoriamente:", opts:["passar pelos pulmões, onde libera o CO₂ e recebe o O₂, antes de ser bombeado de novo","passar pelo fígado, que fabrica oxigênio","ficar parado nas veias até se purificar","passar pelo intestino, que absorve o ar"], a:0, exp:"É a pequena circulação: coração → pulmões (trocas gasosas) → coração → corpo. Nenhum outro órgão oxigena o sangue." }
  ] },
  "cie-10": { q: [
    { t:"fix", q:"As vacinas protegem o corpo porque:", opts:["matam todas as bactérias do organismo na hora da aplicação","são antibióticos de efeito prolongado","apresentam ao corpo partes ou formas enfraquecidas do agente, ensinando as defesas a reconhecê-lo","substituem a necessidade de higiene pessoal"], a:2, exp:"A vacina estimula o sistema imunológico a produzir anticorpos e células de memória contra aquele agente, sem causar a doença." },
    { t:"fix", q:"Doenças como a gripe e a covid-19 são causadas por:", opts:["bactérias","fungos","carência de vitaminas","vírus"], a:3, exp:"Gripe e covid-19 são viroses: causadas por vírus, que só se multiplicam dentro das células. Antibióticos não funcionam contra vírus." },
    { t:"apl", q:"O médico receitou antibiótico para a infecção de garganta de Paulo, causada por uma bactéria, mas não receitou o mesmo remédio para o resfriado dele. A razão é que:", opts:["o resfriado é causado por vírus, e antibióticos não agem contra vírus","o resfriado é grave demais para antibióticos","antibióticos só funcionam em adultos","o antibiótico faria o vírus do resfriado se multiplicar"], a:0, exp:"Antibióticos combatem bactérias. Usá-los contra viroses não ajuda em nada e ainda favorece o surgimento de bactérias resistentes." },
    { t:"apl", q:"Além da vacinação, uma medida simples e comprovada para reduzir a transmissão de doenças respiratórias na escola é:", opts:["tomar vitamina C todos os dias","lavar as mãos com frequência e cobrir boca e nariz ao tossir","usar casaco em dias frios","evitar as aulas de educação física"], a:1, exp:"A higiene das mãos e a etiqueta respiratória quebram a cadeia de transmissão de vírus e bactérias entre as pessoas." },
    { t:"des", q:"Quando grande parte de uma comunidade se vacina, até as pessoas que não puderam tomar a vacina ficam mais protegidas. Isso ocorre porque:", opts:["as vacinas se espalham pelo ar entre as pessoas","os não vacinados criam anticorpos por conta própria","com menos pessoas podendo adoecer e transmitir, o agente circula menos — é a chamada imunidade coletiva","o vírus desiste de circular em cidades vacinadas"], a:2, exp:"É a imunidade coletiva: com a maioria vacinada, o agente encontra poucos hospedeiros, a transmissão cai e quem não pode se vacinar fica indiretamente protegido." }
  ] },
  "cie-11": { q: [
    { t:"fix", q:"O percurso correto do alimento no sistema digestório, depois de engolido, é:", opts:["boca → estômago → esôfago → intestinos","esôfago → intestino grosso → estômago → intestino delgado","esôfago → intestino delgado → estômago → intestino grosso","esôfago → estômago → intestino delgado → intestino grosso"], a:3, exp:"Engolido, o alimento desce pelo esôfago, passa pelo estômago, segue para o intestino delgado (digestão e absorção) e termina no intestino grosso." },
    { t:"apl", q:"Depois do almoço, os nutrientes absorvidos no intestino delgado chegam aos músculos das pernas. O sistema responsável por esse transporte é o:", opts:["sistema respiratório","sistema circulatório","sistema digestório","sistema nervoso"], a:1, exp:"O sangue, do sistema circulatório, carrega nutrientes e oxigênio para todas as células do corpo, incluindo os músculos." },
    { t:"apl", q:"Em um jogo de futebol, os músculos de Rafa precisam de muito oxigênio. O oxigênio do ar chega às células dos músculos por meio de:", opts:["digestão de alimentos ricos em oxigênio","filtragem do ar feita pelos rins","trocas gasosas nos alvéolos e transporte pelo sangue","absorção do ar pela pele durante o jogo"], a:2, exp:"O O₂ entra nos alvéolos, passa para o sangue e é levado às células — uma parceria entre os sistemas respiratório e circulatório." },
    { t:"des", q:"O corpo mantém condições internas estáveis (temperatura, quantidade de água e de açúcar no sangue) mesmo quando o ambiente muda — é a chamada homeostase. Um exemplo desse equilíbrio em ação é:", opts:["suarmos quando faz calor, pois a evaporação do suor ajuda a baixar a temperatura do corpo","sentirmos fome depois de muito tempo sem comer","dormirmos quando anoitece","crescermos alguns centímetros por ano"], a:0, exp:"O suor é um mecanismo de homeostase: ao evaporar, retira calor da pele e mantém a temperatura corporal perto de 36,5 °C." },
    { t:"des", q:"Uma pessoa vacinada contra o sarampo entra em contato com o vírus da doença. No corpo dela, a sequência mais provável é:", opts:["o vírus é digerido pelo estômago antes de infectar as células","o vírus se multiplica livremente, mas a febre o elimina","nada acontece, pois as vacinas impedem o vírus de entrar no corpo","as células de defesa, já preparadas pela vacina, reconhecem o vírus e o combatem rapidamente, antes que a doença se instale"], a:3, exp:"A vacina deixa memória imunológica: no contato real, anticorpos e células de defesa respondem rápido e eliminam o vírus, em geral sem que a pessoa adoeça." }
  ] }
});
