/* Banco de questões — História (7º ano) — gerado para o protótipo Trilha do Saber */
window.QUESTOES = window.QUESTOES || {};
Object.assign(window.QUESTOES, {
  "his-0": { q: [
    { t:"fix", q:"O que foram as capitanias hereditárias, criadas por Portugal em 1534?", opts:["Frotas de navios enviadas para caçar piratas franceses no litoral","Grandes faixas de terra doadas a particulares, com a missão de povoar e administrar a colônia","Fortalezas construídas para defender as cidades do litoral","Impostos pagos pelos colonos diretamente ao rei de Portugal"], a:1, exp:"As capitanias hereditárias eram lotes de terra entregues a donatários, que podiam transmiti-los por herança, em troca de colonizar e explorar a região." },
    { t:"fix", q:"Quem era o donatário de uma capitania hereditária?", opts:["Um funcionário do rei escolhido por eleição entre os colonos","Um líder indígena aliado dos portugueses","Um religioso nomeado pelo papa para cuidar das missões","Um particular que recebia a capitania do rei e podia transmiti-la aos herdeiros"], a:3, exp:"O donatário era um nobre ou fidalgo que recebia a capitania como doação real, com amplos poderes de administrar, cobrar tributos e passar a terra por herança." },
    { t:"apl", q:"Portugal gastava muito com as rotas das Índias e não tinha recursos para ocupar o Brasil, ameaçado por invasores franceses. Por que o rei decidiu criar as capitanias hereditárias?", opts:["Para transferir aos donatários o custo e a responsabilidade de povoar e proteger a terra","Para vender o Brasil à Espanha em parcelas","Para que cada capitania se tornasse um reino independente","Para acabar com o tráfico de escravizados na costa africana"], a:0, exp:"Como a Coroa não tinha dinheiro, entregou a colonização a particulares: assim povoava e defendia o território sem arcar com os custos." },
    { t:"apl", q:"Duas capitanias prosperaram logo no século XVI: Pernambuco e São Vicente. O que elas tinham em comum que explica esse sucesso?", opts:["Abundância de ouro e prata em seus territórios","Ausência total de conflitos com os povos indígenas","Terras férteis e clima adequados ao plantio de cana-de-açúcar","Distância do litoral, que as protegia dos franceses"], a:2, exp:"O cultivo da cana gerava lucros com o açúcar vendido à Europa, e as duas capitanias tinham solo fértil e clima favoráveis a essa lavoura." },
    { t:"des", q:"A maioria das capitanias fracassou por falta de recursos dos donatários, ataques indígenas e invasões francesas. Qual consequência direta esse fracasso teve para a administração da colônia?", opts:["Portugal desistiu do Brasil e devolveu as terras aos povos indígenas","O rei criou o Governo-Geral, em 1549, para centralizar a administração e a defesa da colônia","As capitanias foram vendidas aos holandeses","A capital da colônia foi transferida para o Rio de Janeiro"], a:1, exp:"Diante do fracasso das capitanias, a Coroa criou o Governo-Geral, com sede em Salvador, para coordenar a defesa e a administração de todo o território." }
  ] },
  "his-1": { q: [
    { t:"fix", q:"Na economia açucareira colonial, o que era o engenho?", opts:["O navio que levava o açúcar para a Europa","O imposto pago sobre cada arroba de açúcar","A estrutura onde a cana era moída e transformada em açúcar, com casa-grande e senzala","A feira onde os colonos compravam ferramentas e escravizados"], a:2, exp:"O engenho era o centro da produção açucareira: reunia moenda, casa-grande, senzala e os canaviais ao redor." },
    { t:"fix", q:"Qual grupo formou a principal força de trabalho nos engenhos a partir do fim do século XVI?", opts:["Africanos escravizados, trazidos à força pelo tráfico negreiro","Camponeses portugueses contratados com salário","Prisioneiros de guerra espanhóis","Imigrantes europeus recém-chegados"], a:0, exp:"Os senhores de engenho passaram a usar principalmente africanos escravizados, num sistema marcado por extrema violência e exploração." },
    { t:"apl", q:"Um mapa histórico mostra os engenhos concentrados no litoral do Nordeste, em solos de massapê. Por que essa região foi escolhida para a produção de açúcar?", opts:["Porque havia muitas minas de ferro para fabricar as moendas","Porque a região era vazia e não havia concorrência de outras lavouras","Porque a Coroa obrigava todos os navios a atracar no Nordeste","Porque o solo era fértil, o clima favorecia a cana e o litoral facilitava o escoamento do açúcar"], a:3, exp:"O massapê é um solo muito fértil; o clima quente e úmido e a proximidade dos portos facilitavam a produção e a exportação do açúcar." },
    { t:"apl", q:"Observe as características da economia açucareira: uma única cultura, grandes propriedades e mão de obra escravizada, com produção para a Europa. Essa organização é chamada de:", opts:["plantation de subsistência","sistema de plantation: monocultura, latifúndio e trabalho escravizado voltados para a exportação","feudo, igual ao da Europa medieval","cooperativa agrícola de pequenos agricultores"], a:1, exp:"O plantation combinava monocultura (só cana), latifúndio (terras enormes) e escravidão, com a produção destinada ao mercado europeu." },
    { t:"des", q:"No século XVIII, a produção de açúcar nas Antilhas (Caribe), estimulada pelos holandeses expulsos do Brasil, derrubou o preço do açúcar brasileiro. Somando isso à descoberta do ouro em Minas Gerais, o que aconteceu com a economia colonial?", opts:["O açúcar deixou de ser produzido no Brasil no mesmo ano","O Nordeste se tornou a região mais rica da colônia","O eixo econômico da colônia se deslocou do açúcar do Nordeste para a mineração do Centro-Sul","Portugal proibiu a mineração para salvar os engenhos"], a:2, exp:"Com a concorrência caribenha reduzindo os lucros do açúcar e o ouro surgindo em Minas Gerais, o centro da economia migrou para o Centro-Sul." }
  ] },
  "his-2": { q: [
    { t:"fix", q:"Antes da chegada dos portugueses, os povos indígenas, como os tupinambá, viviam principalmente de:", opts:["grandes plantações de cana para exportação","mineração de ouro nos rios","criação de gado em grandes propriedades","caça, pesca, coleta e agricultura de subsistência, como o cultivo da mandioca"], a:3, exp:"Os povos indígenas praticavam agricultura de coivara (mandioca, milho), além de caça, pesca e coleta, produzindo para o próprio consumo." },
    { t:"fix", q:"Qual foi o objetivo principal dos aldeamentos criados pelos padres jesuítas no Brasil colonial?", opts:["Explorar minas de ouro com trabalho indígena","Catequizar os indígenas, convertendo-os ao catolicismo e aos costumes europeus","Treinar exércitos indígenas para lutar contra a Espanha","Vender terras indígenas aos colonos"], a:1, exp:"Nos aldeamentos, os jesuítas reuniam os indígenas para convertê-los ao cristianismo e ensinar costumes europeus, como a língua portuguesa e novos ofícios." },
    { t:"apl", q:"Os colonos queriam escravizar os indígenas para trabalhar nos engenhos, mas os jesuítas se opunham e defendiam os aldeamentos. O que esse conflito revela?", opts:["Que os colonos respeitavam as leis que proibiam a escravidão indígena","Que a Coroa proibiu imediatamente qualquer contato com os indígenas","Que havia interesses diferentes: os colonos queriam mão de obra escravizada, e os jesuítas queriam catequizar e controlar os aldeamentos","Que os indígenas não participavam de forma alguma da vida colonial"], a:2, exp:"Colonos e jesuítas disputavam os indígenas: uns os queriam como mão de obra escravizada; os outros, como fiéis a converter e manter nos aldeamentos." },
    { t:"apl", q:"Para fugir da escravização e das doenças trazidas pelos europeus, muitos grupos indígenas recuaram para o interior do território. Essa atitude é um exemplo de:", opts:["resistência indígena à colonização","aliança militar com a França contra Portugal","participação no governo das capitanias","conversão voluntária ao catolicismo"], a:0, exp:"Recuar para o sertão foi uma forma de resistência: preservar terras, cultura e liberdade diante do avanço dos colonizadores." },
    { t:"des", q:"Entre os séculos XVI e XVII, a população indígena do litoral diminuiu drasticamente por guerras, escravização e, principalmente, epidemias de doenças europeias. Por que as epidemias foram tão devastadoras, e qual foi uma consequência direta para a colônia?", opts:["Os indígenas já conheciam essas doenças, e a consequência foi o fim dos engenhos","Os europeus também morriam em massa, e a consequência foi a independência da colônia","As doenças se espalharam apenas no interior, e a consequência foi a criação das capitanias","Os indígenas não tinham anticorpos contra doenças como varíola e sarampo; com a falta de mão de obra, os colonos intensificaram o tráfico de africanos escravizados"], a:3, exp:"Sem imunidade, os indígenas morreram em massa; a queda da mão de obra disponível foi um dos fatores que levaram os colonos a ampliar a escravização de africanos." }
  ] },
  "his-3": { q: [
    { t:"fix", q:"Em 1549, Portugal criou o Governo-Geral e nomeou Tomé de Sousa como primeiro governador. Qual cidade foi escolhida como capital da colônia?", opts:["Salvador","Rio de Janeiro","São Vicente","Olinda"], a:0, exp:"Salvador foi fundada em 1549 para ser a sede do Governo-Geral e a primeira capital do Brasil, posição que manteve até 1763." },
    { t:"apl", q:"Ligando os fatos: as capitanias fracassaram e, em seguida, a Coroa criou o Governo-Geral. O que essa mudança revela sobre a política portuguesa?", opts:["Que Portugal decidiu dar independência às capitanias","Que Portugal abandonou a colônia para cuidar apenas da África","Que Portugal passou a controlar a colônia de forma mais direta e centralizada","Que Portugal vendeu a administração da colônia aos holandeses"], a:2, exp:"O Governo-Geral representou maior controle direto da Coroa sobre a colônia, reduzindo a autonomia dos donatários." },
    { t:"apl", q:"Num engenho de Pernambuco do século XVII, a cana era plantada por escravizados e o açúcar ia para a Europa. Quando os holandeses passaram a produzir açúcar nas Antilhas, por que isso preocupava os senhores de engenho brasileiros?", opts:["Porque os holandeses proibiram o plantio de cana no Brasil","Porque a concorrência das Antilhas derrubava o preço do açúcar brasileiro no mercado europeu","Porque os holandeses queriam transformar os engenhos em igrejas","Porque as Antilhas ficavam dentro do território brasileiro"], a:1, exp:"Com mais açúcar à venda no mercado europeu, o preço caía e os lucros dos engenhos brasileiros diminuíam." },
    { t:"des", q:"A capitania de Pernambuco prosperou, enquanto outras enfrentaram grandes dificuldades. Combinando o que se sabe sobre donatários, solo e mercado, qual explicação é a mais completa?", opts:["Pernambuco tinha ouro, enquanto as outras só tinham cana","Pernambuco ficava longe do mar, protegida de invasores","Pernambuco não teve donatário, o que atraiu colonos","Pernambuco uniu donatário com recursos, solo de massapê e açúcar valorizado na Europa; onde faltaram recursos e condições, as capitanias fracassaram"], a:3, exp:"O sucesso dependia de vários fatores juntos: investimento do donatário, terra fértil, clima favorável e um produto com preço alto na Europa." },
    { t:"des", q:"Capitanias, engenhos de açúcar e escravização de indígenas e africanos formaram a base do Brasil Colônia. Qual herança desse período ainda marca o Brasil atual, segundo os historiadores?", opts:["A concentração de terras e de riqueza e a desigualdade social ligada à escravidão","A divisão do Brasil em quinze reinos independentes","A proibição do cultivo de cana que dura até hoje","A ausência de influência das culturas indígena e africana"], a:0, exp:"O latifúndio e a escravidão coloniais deixaram como legado a concentração fundiária e profundas desigualdades sociais que persistem até hoje." }
  ] },
  "his-4": { q: [
    { t:"fix", q:"O que era o Pacto Colonial (ou exclusivo colonial)?", opts:["Um tratado de paz entre Brasil e Espanha","A obrigação de a colônia comercializar apenas com a metrópole, Portugal","A aliança militar entre colonos e povos indígenas","O acordo que dividia o Brasil em capitanias"], a:1, exp:"Pelo Pacto Colonial, a colônia só podia vender e comprar produtos por meio de Portugal, o que garantia os lucros da metrópole." },
    { t:"fix", q:"Qual imposto colonial correspondia a 20% (um quinto) de todo o ouro extraído, pago à Coroa portuguesa?", opts:["O quinto","A derrama","O dízimo","A capitação"], a:0, exp:"O quinto reservava à Coroa 20% de todo o ouro das minas; já a derrama era a cobrança forçada de impostos atrasados." },
    { t:"apl", q:"Em 1789, a Coroa anunciou a derrama em Minas Gerais: uma cobrança para quitar os impostos atrasados da mineração, que estava em decadência. Como parte da elite mineira reagiu?", opts:["Pagou tudo imediatamente e sem protestos","Entregou Minas Gerais ao controle da Espanha","Fundou novas capitanias hereditárias no interior","Organizou a Inconfidência Mineira, um movimento que pretendia romper com Portugal"], a:3, exp:"A derrama revoltou a elite mineira e foi um dos estopins da Inconfidência Mineira, conspirada em Vila Rica e liderada por figuras como Tiradentes." },
    { t:"apl", q:"No fim do século XVIII, circulavam na colônia as ideias do Iluminismo e a notícia da independência dos Estados Unidos (1776). Por que essas ideias alimentaram movimentos contra Portugal?", opts:["Porque ensinavam novas técnicas de mineração","Porque proibiam o comércio com outros países","Porque defendiam liberdade, igualdade e o direito de os povos escolherem seus governos","Porque obrigavam os colonos a se mudar para a Europa"], a:2, exp:"O Iluminismo e o exemplo norte-americano mostravam que era possível romper com a metrópole e construir um governo próprio, inspirando os colonos." },
    { t:"des", q:"A Inconfidência Mineira (1789) envolveu principalmente a elite letrada; já a Conjuração Baiana (1798) reuniu pobres, mulatos, soldados e alfaiates que defendiam até o fim da escravidão. O que essa diferença revela sobre a crise do sistema colonial?", opts:["Que apenas a elite mineira pagava impostos à Coroa","Que a insatisfação com o domínio português se espalhava por diferentes grupos sociais, com propostas cada vez mais populares","Que a Conjuração Baiana era um movimento organizado pelos jesuítas","Que a Inconfidência queria devolver o poder aos donatários"], a:1, exp:"Os dois movimentos mostram a crise avançando: da elite mineira para setores populares baianos, que incluíam pautas sociais como o fim da escravidão." }
  ] },
  "his-5": { q: [
    { t:"fix", q:"Quando e onde ocorreu o grito do Ipiranga, símbolo da Independência do Brasil?", opts:["Em 15 de novembro de 1889, no Rio de Janeiro","Em 22 de abril de 1500, em Porto Seguro","Em 7 de setembro de 1822, às margens do riacho Ipiranga, em São Paulo","Em 13 de maio de 1888, no Palácio Imperial"], a:2, exp:"D. Pedro proclamou a independência em 7 de setembro de 1822, episódio conhecido como grito do Ipiranga." },
    { t:"fix", q:"O que foi o Dia do Fico (9 de janeiro de 1822)?", opts:["O dia em que D. Pedro abdicou do trono do Brasil","O dia em que a família real portuguesa chegou ao Brasil","O dia em que foi assinada a Lei Áurea","O dia em que D. Pedro declarou que ficaria no Brasil, contrariando as ordens das Cortes portuguesas"], a:3, exp:"No Dia do Fico, D. Pedro desobedeceu às Cortes de Lisboa, que exigiam seu retorno a Portugal, e anunciou que permaneceria no Brasil." },
    { t:"apl", q:"Depois que a família real voltou a Portugal, as Cortes de Lisboa tentaram rebaixar o Brasil novamente à condição de colônia, anulando as decisões de D. Pedro. Por que isso acelerou a independência?", opts:["Porque os brasileiros concordaram em voltar ao Pacto Colonial","Porque uniu os brasileiros, indignados com a perda de autonomia, em torno de D. Pedro","Porque a Espanha invadiu o Rio de Janeiro para apoiar as Cortes","Porque D. Pedro decidiu voltar a Portugal imediatamente"], a:1, exp:"A tentativa de recolonização revoltou elites e população, que passaram a apoiar o rompimento definitivo com Portugal." },
    { t:"apl", q:"José Bonifácio de Andrada e Silva foi um dos principais conselheiros de D. Pedro. Qual foi o papel dele no processo de independência?", opts:["Orientou politicamente D. Pedro, articulou o apoio das elites e tornou-se ministro do novo Império","Comandou as tropas portuguesas que resistiam em Lisboa","Foi o último governador-geral do período colonial","Proclamou a República brasileira em 1889"], a:0, exp:"José Bonifácio aconselhou D. Pedro a romper com Portugal e organizou politicamente o novo país, ficando conhecido como Patriarca da Independência." },
    { t:"des", q:"Na América Espanhola, as independências geraram vários países e longas guerras. No Brasil, o processo foi relativamente rápido e manteve a unidade territorial e a monarquia. Qual explicação combina corretamente os fatores?", opts:["O Brasil nunca foi colônia, então não precisou lutar","A Espanha ajudou militarmente o Brasil a se libertar de Portugal","Como o próprio príncipe herdeiro de Portugal liderou o processo, com apoio das elites, houve menos guerra e o país se manteve unido sob a mesma dinastia","A independência brasileira ocorreu por acaso, sem participação de ninguém"], a:2, exp:"A liderança de D. Pedro, herdeiro da Coroa portuguesa, aliada ao apoio das elites, tornou o rompimento menos violento e preservou a unidade e a monarquia." }
  ] },
  "his-6": { q: [
    { t:"fix", q:"Quem foi o primeiro imperador do Brasil, coroado em 1822?", opts:["D. João VI","D. Pedro II","José Bonifácio","D. Pedro I"], a:3, exp:"D. Pedro I tornou-se o primeiro imperador do Brasil ao proclamar a independência, dando início ao Primeiro Reinado." },
    { t:"fix", q:"O que era o Poder Moderador, criado pela Constituição de 1824?", opts:["O poder dos donatários sobre as capitanias","Um poder exercido pelo imperador, acima dos poderes Executivo, Legislativo e Judiciário","O poder dos senhores de engenho sobre os escravizados","Um poder controlado pelas Cortes de Portugal"], a:1, exp:"O Poder Moderador permitia ao imperador intervir nos demais poderes, nomear senadores e dissolver a Câmara, concentrando muita autoridade em suas mãos." },
    { t:"apl", q:"Em 7 de abril de 1831, diante de conflitos com a elite brasileira, crise econômica e pressão popular, D. Pedro I abdicou do trono. Quem assumiu o governo do Império naquele momento?", opts:["Ninguém diretamente: como o herdeiro, D. Pedro II, tinha apenas 5 anos, regentes governaram em seu nome","D. João VI voltou de Portugal para governar","A princesa Isabel foi coroada imperatriz","Deodoro da Fonseca assumiu a presidência"], a:0, exp:"D. Pedro I deixou o trono ao filho de 5 anos; até a maioridade do príncipe, o país foi governado por regências." },
    { t:"apl", q:"Durante o Segundo Reinado (1840–1889), a produção de café cresceu no Vale do Paraíba. Como a expansão cafeeira influenciou o Brasil Império?", opts:["Levou o Brasil a devolver o trono a Portugal","Acabou com as ferrovias do país","O café deu lucros às elites do Centro-Sul, financiou ferrovias e sustentou a estabilidade do Império","O café era plantado apenas para o consumo das famílias"], a:2, exp:"Os lucros do café enriqueceram os cafeicultores, pagaram obras como ferrovias e deram base econômica ao Segundo Reinado." },
    { t:"des", q:"No fim do Império, o exército estava insatisfeito, a Igreja se afastou do imperador e os cafeicultores, contrariados com a abolição, deixaram de apoiar a monarquia. Combinando esses fatores, o que explica a queda de D. Pedro II em 1889?", opts:["Uma invasão espanhola derrubou o imperador","D. Pedro II abdicou para se tornar presidente da Argentina","O povo votou pelo fim da monarquia em um plebiscito nacional","A monarquia perdeu seus principais pilares de apoio — exército, Igreja e cafeicultores — e ficou vulnerável ao golpe republicano"], a:3, exp:"Sem o sustento dos três grupos que a apoiavam, a monarquia ficou isolada e acabou derrubada pelos militares republicanos em 1889." }
  ] },
  "his-7": { q: [
    { t:"fix", q:"Em 1808, a família real portuguesa chegou ao Brasil fugindo das tropas de Napoleão. Qual medida de D. João beneficiou diretamente o comércio da colônia?", opts:["A abertura dos portos às nações amigas","A criação das capitanias hereditárias","A assinatura da Lei Áurea","A proclamação da República"], a:0, exp:"Ao abrir os portos, D. João permitiu o comércio direto com outros países, como a Inglaterra, rompendo o exclusivo colonial." },
    { t:"apl", q:"Ligue causa e efeito: (1) cobrança da derrama; (2) circulação das ideias iluministas; (3) Inconfidência Mineira. Qual encadeamento está correto?", opts:["As ideias iluministas acabaram com a mineração, o que criou a derrama","A Inconfidência Mineira deu origem ao Iluminismo na Europa","A derrama aumentou a insatisfação da elite mineira, que, influenciada pelas ideias iluministas, conspirou pela independência","A derrama foi criada para punir os inconfidentes depois do movimento"], a:2, exp:"A cobrança da derrama e as ideias de liberdade combinaram-se e levaram a elite de Vila Rica a conspirar contra o domínio português." },
    { t:"apl", q:"Em 1815, D. João elevou o Brasil a Reino Unido de Portugal e Algarves. Por que, mesmo assim, muitos brasileiros apoiaram a independência poucos anos depois?", opts:["Porque o Brasil voltou a ser colônia da Espanha","Porque as Cortes portuguesas tentaram rebaixar o Brasil e recolocá-lo sob controle direto de Lisboa","Porque D. João VI proibiu o comércio com a Inglaterra","Porque o Brasil já era uma república desde 1815"], a:1, exp:"As Cortes queriam anular a autonomia conquistada; a ameaça de recolonização uniu os brasileiros em torno do rompimento com Portugal." },
    { t:"des", q:"Um aluno afirmou: «A independência de 1822 mudou tudo no Brasil.» Avaliando economia, política e sociedade, qual análise está correta?", opts:["A afirmação está certa: a escravidão acabou em 1822","A afirmação está certa: o Brasil virou república em 1822","A afirmação está errada: Portugal continuou governando até 1889","A afirmação é parcial: houve mudança política, mas a escravidão, o latifúndio e o poder das elites continuaram os mesmos"], a:3, exp:"A independência rompeu com Portugal, mas manteve a estrutura escravista e latifundiária; as grandes mudanças sociais vieram só muito depois." },
    { t:"des", q:"Coloque em ordem cronológica: (I) abdicação de D. Pedro I; (II) Brasil elevado a Reino Unido; (III) Dia do Fico; (IV) independência.", opts:["II, III, IV, I","I, II, III, IV","III, II, I, IV","IV, III, II, I"], a:0, exp:"Reino Unido em 1815, Dia do Fico em janeiro de 1822, independência em setembro de 1822 e abdicação em 1831: II, III, IV, I." }
  ] },
  "his-8": { q: [
    { t:"fix", q:"O que foi o Período Regencial (1831–1840)?", opts:["O período em que D. João VI governou de Lisboa","O período em que regentes governaram o Brasil porque D. Pedro II ainda era criança","O período das primeiras capitanias hereditárias","O governo dos primeiros presidentes após a República"], a:1, exp:"Após a abdicação de D. Pedro I, como o herdeiro tinha apenas 5 anos, regentes assumiram o governo até 1840." },
    { t:"fix", q:"Qual revolta do período regencial ocorreu no Rio Grande do Sul e durou cerca de dez anos (1835–1845)?", opts:["Sabinada","Cabanagem","Balaiada","Revolução Farroupilha"], a:3, exp:"A Revolução Farroupilha foi a mais longa revolta regencial e chegou a proclamar a República Rio-Grandense." },
    { t:"apl", q:"Os gaúchos produziam charque (carne-seca) para abastecer os engenhos, mas o produto importado da Argentina e do Uruguai entrava no Brasil com menos impostos e mais barato. Como os produtores gaúchos reagiram?", opts:["Rebelaram-se na Revolução Farroupilha, exigindo proteção para o charque local","Mudaram-se todos para a Europa","Passaram a plantar café em Minas Gerais","Apoiaram a volta de D. Pedro I ao trono"], a:0, exp:"Prejudicados pela concorrência do charque platino, os estancieiros gaúchos iniciaram a Revolução Farroupilha em 1835." },
    { t:"apl", q:"Na Cabanagem (Pará, 1835–1840), os cabanos — indígenas, mestiços e pobres — tomaram Belém e enfrentaram a elite local. O que essa revolta teve de particular em relação às demais?", opts:["Foi a única revolta pacífica, sem nenhum conflito","Foi liderada pessoalmente por D. Pedro II","Teve enorme participação popular e provocou milhares de mortes entre os mais pobres","Ocorreu fora do território brasileiro"], a:2, exp:"A Cabanagem destacou-se pela forte participação das camadas pobres e pela violência: estima-se que grande parte da população do Grão-Pará tenha morrido." },
    { t:"des", q:"Por que o Período Regencial foi palco de tantas revoltas, como Cabanagem, Balaiada, Sabinada e Farroupilha? Combine: disputas entre liberais e conservadores, pobreza regional, desejo de autonomia das províncias e ausência de um imperador adulto.", opts:["Porque D. Pedro II reprimia pessoalmente as províncias com violência","Porque a instabilidade política do governo regencial e as desigualdades regionais criaram terreno para revoltas com pautas locais e populares","Porque Portugal enviou tropas para recolonizar o Brasil","Porque todas as províncias queriam ser anexadas pelos Estados Unidos"], a:1, exp:"Sem um imperador adulto e com disputas políticas intensas, as insatisfações regionais explodiram em revoltas por todo o país." }
  ] },
  "his-9": { q: [
    { t:"fix", q:"Qual lei, assinada pela princesa Isabel em 13 de maio de 1888, declarou extinta a escravidão no Brasil?", opts:["Lei do Ventre Livre","Lei dos Sexagenários","Lei Áurea","Lei Eusébio de Queirós"], a:2, exp:"A Lei Áurea libertou os escravizados que ainda restavam e fez do Brasil o último país das Américas a abolir a escravidão." },
    { t:"fix", q:"O que determinava a Lei do Ventre Livre, de 1871?", opts:["Que os filhos de mulheres escravizadas nascidos a partir de então seriam livres","Que todos os escravizados eram libertados imediatamente","Que o tráfico de africanos passava a ser legal","Que os escravizados com mais de 60 anos recebiam terras"], a:0, exp:"A Lei do Ventre Livre declarava livres as crianças filhas de escravizadas nascidas depois de 1871, um passo gradual rumo à abolição." },
    { t:"apl", q:"Em 1850, a Lei Eusébio de Queirós proibiu o tráfico de africanos escravizados para o Brasil, sob forte pressão da Inglaterra. Por que os ingleses pressionavam pelo fim do tráfico?", opts:["Por pura solidariedade aos africanos, sem nenhum interesse próprio","Para que o Brasil comprasse escravizados da Espanha","Para vender armas aos senhores de engenho","Porque a indústria inglesa queria ampliar seus mercados consumidores, e a escravidão limitava o consumo"], a:3, exp:"Já industrializada, a Inglaterra precisava de mercados com consumidores livres e assalariados; por isso passou a combater o tráfico negreiro." },
    { t:"apl", q:"Joaquim Nabuco, José do Patrocínio, Luís Gama e os milhares de escravizados que fugiam para quilombos têm algo em comum na história da abolição. O quê?", opts:["Todos foram imperadores do Brasil","Todos lutaram, cada um a seu modo, contra a escravidão e pelo fim desse sistema","Todos defendiam a volta do tráfico negreiro","Todos eram senhores de engenho do Nordeste"], a:1, exp:"Abolicionistas, jornalistas, advogados como Luís Gama — que libertava escravizados pelos tribunais — e fugitivos dos quilombos formaram a resistência que desgastou a escravidão." },
    { t:"des", q:"A Lei Áurea libertou os escravizados, mas não garantiu terra, trabalho ou educação aos libertos. Unindo isso ao preconceito da sociedade da época, qual foi a consequência para a população negra brasileira nas décadas seguintes?", opts:["Os libertos se tornaram imediatamente donos de grandes fazendas","Todos os libertos voltaram à África com indenizações do governo","A exclusão social persistiu: sem recursos nem políticas de integração, os libertos ficaram marginalizados, herança que ajuda a explicar desigualdades até hoje","A escravidão voltou a ser legal em 1900"], a:2, exp:"Libertos sem terra, emprego digno ou educação foram empurrados para a pobreza; a abolição incompleta ajuda a explicar o racismo e a desigualdade atuais." }
  ] },
  "his-10": { q: [
    { t:"fix", q:"Quem proclamou a República do Brasil, em 15 de novembro de 1889?", opts:["D. Pedro II","Princesa Isabel","Getúlio Vargas","Marechal Deodoro da Fonseca"], a:3, exp:"O marechal Deodoro da Fonseca liderou o golpe militar que derrubou a monarquia e se tornou o primeiro presidente do Brasil." },
    { t:"fix", q:"O que aconteceu com a família imperial após a proclamação da República?", opts:["Foi coroada novamente um ano depois","Foi exilada na Europa","Passou a governar as províncias do Norte","Ficou presa em Fernando de Noronha por dez anos"], a:1, exp:"D. Pedro II e sua família foram obrigados a deixar o Brasil e partir para o exílio na Europa, onde o imperador morreu em 1891." },
    { t:"apl", q:"Depois da abolição, muitos cafeicultores ficaram contrariados com a monarquia por não terem recebido indenização pelos escravizados libertados. Como isso contribuiu para a proclamação da República?", opts:["Os cafeicultores compraram o trono para D. Pedro II","Os cafeicultores declararam guerra à Inglaterra","Os cafeicultores passaram a apoiar os republicanos, retirando da monarquia um de seus principais sustentáculos","Os cafeicultores perderam toda a influência política no país"], a:2, exp:"Ressentidos com a abolição sem indenização, os cafeicultores aderiram à causa republicana, o que enfraqueceu ainda mais o Império." },
    { t:"apl", q:"Além dos cafeicultores, outros dois grupos se afastaram da monarquia: os militares (Questão Militar) e o clero (Questão Religiosa). O que essas duas crises tinham em comum?", opts:["Eram disputas entre o governo imperial e instituições que antes apoiavam o trono, o que isolou D. Pedro II","Eram guerras contra países vizinhos","Eram revoltas de escravizados contra os engenhos","Eram eleições fraudadas pelos republicanos"], a:0, exp:"Nas duas crises, o imperador entrou em conflito com o exército e com a Igreja, perdendo apoios fundamentais da monarquia." },
    { t:"des", q:"Um escritor da época afirmou que o povo «assistiu bestializado» à proclamação da República. Relacionando isso ao modo como o regime mudou, qual interpretação é correta?", opts:["O povo invadiu o palácio e depôs o imperador em meio a festas","A República foi proclamada por votação popular em todas as províncias","O povo derrubou Deodoro no dia seguinte à proclamação","A mudança foi um golpe militar articulado por elites; a população não participou e apenas assistiu, surpresa, à troca de regime"], a:3, exp:"A República nasceu de um golpe de militares e elites; sem plebiscito nem mobilização popular, o povo foi mero espectador da mudança." }
  ] },
  "his-11": { q: [
    { t:"fix", q:"Em 1840, o Golpe da Maioridade antecipou a coroação de D. Pedro II, então com 14 anos. Qual foi o objetivo dessa manobra política?", opts:["Acabar com a instabilidade das regências, colocando um imperador no trono","Proclamar a República antes da hora","Devolver o trono a D. Pedro I","Unir o Brasil novamente a Portugal"], a:0, exp:"Com a maioridade antecipada, os políticos esperavam que um imperador no trono pusesse fim às revoltas e à instabilidade do período regencial." },
    { t:"apl", q:"Encadeie os fatos: fim da escravidão em 1888, cafeicultores sem indenização e queda da monarquia em 1889. Como esses fatos se conectam?", opts:["A abolição aumentou os impostos sobre o exército, que depôs Deodoro","A Lei Áurea proibia o plantio de café, e os cafeicultores fundaram quilombos","Contrariados com a abolição, os cafeicultores deixaram de apoiar D. Pedro II e aderiram à República, enfraquecendo a monarquia","Não há relação entre os fatos, pois aconteceram em séculos diferentes"], a:2, exp:"A abolição sem indenização afastou os cafeicultores do imperador; sem esse apoio, a monarquia caiu no ano seguinte." },
    { t:"apl", q:"Na Balaiada (Maranhão, 1838–1841), participaram vaqueiros, escravizados, indígenas e pobres, liderados por figuras como Raimundo Gomes e Cosme. O que essa composição revela sobre as revoltas regenciais?", opts:["Que elas eram organizadas pelo próprio imperador","Que elas reuniram camadas pobres e marginalizadas, com reivindicações sociais além das disputas entre elites","Que nelas participavam apenas senhores de engenho ricos","Que elas ocorreram somente nas cidades do litoral"], a:1, exp:"A Balaiada mostra que as revoltas regenciais envolveram setores populares — negros, indígenas e pobres — com pautas sociais próprias." },
    { t:"des", q:"Coloque em ordem cronológica: (I) Proclamação da República; (II) Golpe da Maioridade; (III) Revolução Farroupilha; (IV) Lei Áurea.", opts:["II, III, IV, I","I, IV, II, III","IV, III, I, II","III, II, IV, I"], a:3, exp:"A Farroupilha começou em 1835, a Maioridade ocorreu em 1840, a Lei Áurea em 1888 e a República em 1889: III, II, IV, I." },
    { t:"des", q:"Compare as revoltas regenciais, como Cabanagem e Balaiada, com a Proclamação da República (1889). Qual é uma diferença fundamental entre elas?", opts:["As revoltas regenciais tiveram ampla participação popular e pautas sociais; a República foi proclamada por militares e elites, sem participação do povo","As revoltas regenciais queriam acabar com o café; a República queria acabar com o açúcar","A República de 1889 devolveu o poder aos donatários das capitanias","As revoltas regenciais ocorreram depois de 1889"], a:0, exp:"Enquanto as revoltas regenciais contaram com massas populares lutando por demandas sociais, a República nasceu de um golpe de elites e militares, sem o povo." }
  ] }
});
