/* Banco de questões — Língua Portuguesa (7º ano) — gerado para o protótipo Trilha do Saber */
window.QUESTOES = window.QUESTOES || {};
Object.assign(window.QUESTOES, {
  "por-0": { q: [
    { t:"fix", q:"A crônica é um gênero textual que, em geral, apresenta:", opts:["instruções passo a passo para realizar uma tarefa","um texto curto sobre fatos do cotidiano, com olhar subjetivo, crítico ou bem-humorado","versos com rima e métrica fixas","informações objetivas sobre um acontecimento recente, sem nenhuma opinião"], a:1, exp:"A crônica é um texto curto que parte do dia a dia e mistura narração, opinião e humor. Isso a diferencia da notícia, que informa com objetividade." },
    { t:"fix", q:"Qual destas características é típica da crônica?", opts:["linguagem técnica e impessoal","estrutura de verbete organizado em ordem alfabética","temas simples do dia a dia tratados com leveza e reflexão","presença obrigatória de versos e rimas"], a:2, exp:"O cronista pega cenas comuns, como a fila da padaria ou o trânsito, e as transforma em reflexão com linguagem leve e pessoal." },
    { t:"apl", q:"Marina escreveu um texto curto, em primeira pessoa, contando com humor o sufoco de esperar o ônibus atrasado e, no final, fez uma crítica à falta de respeito com os passageiros. O texto de Marina é:", opts:["uma crônica","uma notícia","um anúncio publicitário","uma receita"], a:0, exp:"Texto curto, em primeira pessoa, sobre um fato cotidiano, com humor e crítica no desfecho: são as marcas da crônica." },
    { t:"apl", q:"Um cronista transforma uma cena banal — a fila da padaria — em uma reflexão sobre a pressa das pessoas. Essa escolha mostra que a crônica:", opts:["precisa de dados estatísticos para convencer","deve esconder a opinião de quem escreve","só trata de acontecimentos raros e extraordinários","parte do cotidiano e revela um olhar atento e pessoal sobre ele"], a:3, exp:"A força da crônica está justamente em olhar com atenção para o que parece comum e tirar daí uma reflexão pessoal." },
    { t:"des", q:"Leia o fragmento: «O elevador quebrou de novo. Fiquei vinte minutos entre o vizinho do 302 e a moça do piano, descobrindo que a gente só conversa quando a tecnologia falha.» Esse texto é uma crônica porque:", opts:["narra um acidente grave com informações oficiais","apresenta versos com rimas no final","parte de um fato banal do cotidiano para refletir, com humor, sobre o comportamento das pessoas","apresenta dados técnicos sobre o funcionamento de elevadores"], a:2, exp:"O texto junta duas marcas da crônica: um fato corriqueiro (o elevador quebrado) e uma reflexão bem-humorada sobre as relações humanas." }
  ] },
  "por-1": { q: [
    { t:"fix", q:"Leia o texto: Seu Arnaldo vende pipoca na esquina há trinta anos. Conhece cada cliente pelo nome e pelo gosto: dona Cida quer sal, Rui prefere doce. Quando o cinema do bairro fechou, muita gente achou que ele fosse embora. Ele ficou. «Cinema fecha, mas fome de pipoca não passa», diz ele, sorrindo. Na verdade, acho que Seu Arnaldo não vende pipoca: vende companhia. Segundo o texto, há quanto tempo Seu Arnaldo vende pipoca na esquina?", opts:["há treze anos","há trinta anos","há três anos","há cinquenta anos"], a:1, exp:"A informação está explícita na primeira frase do texto: ele vende pipoca na esquina há trinta anos." },
    { t:"fix", q:"No texto do pipoqueiro (questão anterior), o que aconteceu com o cinema do bairro?", opts:["foi totalmente reformado","mudou de dono","fechou","virou um supermercado"], a:2, exp:"O texto diz diretamente: «quando o cinema do bairro fechou». Essa é uma informação explícita, que não exige dedução." },
    { t:"apl", q:"No texto do pipoqueiro, muita gente achou que Seu Arnaldo fosse embora quando o cinema fechou, mas ele ficou. Esse trecho sugere que:", opts:["o trabalho dele ia além do dinheiro: havia vínculo com o bairro e com as pessoas","ele não tinha para onde ir","ele tinha medo de procurar outro emprego","o cinema o contratou para trabalhar lá"], a:0, exp:"A permanência dele, somada ao fato de conhecer cada cliente pelo nome, permite deduzir que o que o prendia ali era o vínculo com as pessoas." },
    { t:"apl", q:"Na frase final, o narrador afirma que Seu Arnaldo «não vende pipoca: vende companhia». Com isso, ele quer dizer que o pipoqueiro:", opts:["cobra caro demais pela pipoca","trabalha sempre acompanhado da família","vende ingressos para o cinema","oferece, mais do que pipoca, atenção e amizade aos clientes"], a:3, exp:"É uma interpretação de sentido figurado: a «companhia» resume o atendimento próximo e amigável, que vale mais que o produto." },
    { t:"des", q:"Qual é o tema principal do texto do pipoqueiro e que recurso o autor usa para construí-lo?", opts:["a crise dos cinemas de bairro, construída com dados estatísticos","o valor das relações humanas no cotidiano, construído pelo contraste entre vender pipoca e vender companhia","receitas de pipoca doce e salgada, explicadas com linguagem técnica","a história de um bairro antigo, contada com datas e fatos oficiais"], a:1, exp:"É preciso combinar duas leituras: o tema (a amizade no dia a dia) e o recurso (o contraste final entre pipoca e companhia), que fecha o texto com o sentido figurado." }
  ] },
  "por-2": { q: [
    { t:"fix", q:"O que são conectivos (ou elementos coesivos)?", opts:["sinais de pontuação usados no final das frases","palavras difíceis retiradas do dicionário","palavras ou expressões que ligam frases e ideias, dando sentido ao texto, como «porque», «mas» e «então»","palavras de língua estrangeira usadas no texto"], a:2, exp:"Conectivos são as «pontes» do texto: ligam orações e parágrafos e mostram relações como causa, oposição e conclusão." },
    { t:"fix", q:"Na frase «Choveu muito, por isso o jogo foi cancelado», o conectivo «por isso» expressa uma relação de:", opts:["consequência","oposição","comparação","dúvida"], a:0, exp:"O cancelamento do jogo é consequência da chuva. «Por isso» liga uma causa ao seu resultado." },
    { t:"apl", q:"Complete a frase: «Estudei bastante, ______ não fui bem na prova.» O conectivo que preenche corretamente o espaço, expressando contraste, é:", opts:["porque","portanto","e","mas"], a:3, exp:"Há contraste entre estudar bastante e não ir bem: o conectivo de oposição adequado é «mas». «Porque» indicaria causa e «portanto», conclusão." },
    { t:"apl", q:"Paulo escreveu duas frases soltas: «O ônibus atrasou. Cheguei tarde à escola.» Para ligá-las mostrando a relação de causa e efeito, ele deve escrever:", opts:["O ônibus atrasou, mas cheguei cedo à escola.","Cheguei tarde à escola porque o ônibus atrasou.","O ônibus atrasou, ou cheguei tarde à escola.","O ônibus atrasou, apesar de eu chegar tarde à escola."], a:1, exp:"«Porque» apresenta a causa (o atraso do ônibus) do efeito (chegar tarde). As outras opções usam conectivos de oposição ou alternância, que não combinam com o sentido." },
    { t:"des", q:"Leia: «Ana comprou mangas. Elas estavam maduras, mas caras.» No trecho, a palavra «elas» e o conectivo «mas» têm, respectivamente, as funções de:", opts:["retomar um termo já citado, evitando repetição, e indicar oposição entre duas ideias","introduzir uma explicação e indicar conclusão","apresentar uma informação nova e indicar comparação","expressar dúvida e indicar finalidade"], a:0, exp:"Dois passos: perceber que «elas» retoma «mangas» (coesão por referência) e que «mas» opõe «maduras» a «caras» (coesão por oposição)." }
  ] },
  "por-3": { q: [
    { t:"fix", q:"Qual alternativa reúne apenas características da crônica?", opts:["versos, rimas e refrão","dados estatísticos e imparcialidade","tabelas, legendas e fontes","texto curto, tema do cotidiano, linguagem próxima da fala e tom crítico ou bem-humorado"], a:3, exp:"A crônica combina texto breve, assunto do dia a dia, linguagem leve e uma opinião pessoal, muitas vezes com humor." },
    { t:"apl", q:"Leia: «No supermercado, a fila andava devagar. Cada um olhava o próprio celular, hipnotizado. Quando o caixa sorriu e puxou conversa, a fila inteira acordou.» A crítica presente nessa crônica é dirigida:", opts:["à lentidão dos caixas do supermercado","ao isolamento das pessoas por causa do celular","ao preço alto dos produtos","ao sorriso do caixa"], a:1, exp:"O contraste entre todos «hipnotizados» no celular e a fila que «acordou» com uma conversa mostra a crítica ao isolamento causado pelas telas." },
    { t:"apl", q:"Complete a frase com o conectivo adequado: «O caixa estava cansado, ______ sorriu para todos os clientes.»", opts:["porque","por isso","mesmo assim","e depois"], a:2, exp:"«Mesmo assim» indica oposição: apesar do cansaço, ele sorriu. «Porque» daria ideia de causa e «por isso», de consequência, o que inverteria o sentido." },
    { t:"des", q:"Leia: «Todo dia o cachorro do vizinho latia para o portão. Ontem, porém, ele silenciou: o portão foi trocado por um muro.» Nesse fragmento de crônica, a palavra «porém» e o desfecho indicam, respectivamente:", opts:["uma oposição e um desfecho bem-humorado, típico do gênero","uma causa e um final trágico","uma conclusão e uma explicação científica","uma comparação e um mistério policial"], a:0, exp:"É preciso reconhecer duas coisas: «porém» marca oposição, e a solução exagerada (trocar o portão por um muro) cria o humor característico da crônica." },
    { t:"des", q:"Leia: «Comprei um despertador novo para não perder a hora. Ele toca tão baixo que continuo chegando atrasado, mas agora com a consciência tranquila de quem tentou.» O humor desse texto nasce:", opts:["do medo que o narrador sente do novo relógio","da descrição técnica e detalhada do despertador","do contraste entre a intenção de mudar e o resultado igual, com uma autocrítica bem-humorada","da raiva do narrador contra os vizinhos barulhentos"], a:2, exp:"O narrador ri de si mesmo: a solução não resolveu nada, e ele se consola com a «consciência tranquila». Identificar o humor exige perceber esse contraste." }
  ] },
  "por-4": { q: [
    { t:"fix", q:"Na frase «A menina correu no parque», a palavra «menina» é um:", opts:["substantivo","verbo","adjetivo","advérbio"], a:0, exp:"«Menina» dá nome a um ser: é substantivo. «Correu» é o verbo da frase." },
    { t:"fix", q:"Qual destas palavras é um verbo?", opts:["mesa","bonito","rapidamente","cantar"], a:3, exp:"«Cantar» indica ação, portanto é verbo. «Mesa» é substantivo, «bonito» é adjetivo e «rapidamente» é advérbio." },
    { t:"apl", q:"Na frase «O cachorro bravo latiu alto», as palavras «bravo» e «alto» são, respectivamente:", opts:["substantivo e verbo","adjetivo e advérbio","verbo e adjetivo","advérbio e substantivo"], a:1, exp:"«Bravo» caracteriza o substantivo «cachorro» (adjetivo); «alto» modifica o verbo «latiu», indicando o modo da ação (advérbio)." },
    { t:"apl", q:"Na campanha de doação «Doe sangue, doe vida», a palavra «doe» pertence à classe dos:", opts:["substantivos","adjetivos","verbos","advérbios"], a:2, exp:"«Doe» é forma do verbo «doar» no imperativo: expressa uma ação pedida ao leitor. Palavras mudam de classe conforme o uso na frase." },
    { t:"des", q:"Compare as frases: «Cheguei cedo ao cinema.» e «O cedo não garante lugar.» A palavra «cedo» é classificada, respectivamente, como:", opts:["advérbio e substantivo","adjetivo e advérbio","substantivo e verbo","advérbio e adjetivo"], a:0, exp:"Na primeira frase, «cedo» modifica o verbo «cheguei» (advérbio). Na segunda, vem depois do artigo «o» e vira nome de algo: substantivo. A classe depende da função na frase." }
  ] },
  "por-5": { q: [
    { t:"fix", q:"Na frase «Os alunos leram o livro», o sujeito é:", opts:["leram","o livro","os alunos","leram o livro"], a:2, exp:"O sujeito é o termo sobre o qual se declara algo e com o qual o verbo concorda: «os alunos». «Leram o livro» é o predicado." },
    { t:"fix", q:"O predicado de uma frase é:", opts:["a palavra que nomeia pessoas e lugares","aquilo que se declara a respeito do sujeito","o termo que liga duas orações","o nome próprio da pessoa que fala"], a:1, exp:"O predicado é tudo o que se diz sobre o sujeito; normalmente contém o verbo e seus complementos." },
    { t:"apl", q:"Na frase «Choveu muito ontem», o sujeito é:", opts:["inexistente: é uma frase sem sujeito","a chuva","muito","ontem"], a:0, exp:"Verbos que indicam fenômenos da natureza, como «chover», formam orações sem sujeito quando usados nesse sentido." },
    { t:"apl", q:"Na frase «Meu irmão e eu chegamos cedo», o sujeito é composto porque:", opts:["tem um único núcleo","aparece depois do verbo","está oculto na frase","tem dois núcleos: «irmão» e «eu»"], a:3, exp:"Sujeito composto é o que tem mais de um núcleo. Aqui, «irmão» e «eu» são os dois núcleos, e por isso o verbo fica no plural («chegamos»)." },
    { t:"des", q:"Na frase «Chegaram ao museu os visitantes curiosos», o sujeito e o seu núcleo são, respectivamente:", opts:["sujeito: chegaram ao museu; núcleo: museu","sujeito: os visitantes curiosos; núcleo: visitantes","sujeito inexistente","sujeito: ao museu; núcleo: museu"], a:1, exp:"O sujeito pode vir depois do verbo (ordem inversa). Pergunte ao verbo: quem chegou? Os visitantes curiosos. O núcleo é a palavra principal: «visitantes»." }
  ] },
  "por-6": { q: [
    { t:"fix", q:"Complete a frase: «Ela ______ as flores todos os dias.»", opts:["regam","rego","regastes","rega"], a:3, exp:"O sujeito «ela» pede o verbo na 3ª pessoa do singular: «rega». «Regam» é plural e «rego» é 1ª pessoa (eu)." },
    { t:"fix", q:"Assinale a frase com a concordância verbal correta:", opts:["Nós chegamos cedo.","Nós chegou cedo.","Eles chegou cedo.","Eu chegaram cedo."], a:0, exp:"O verbo deve concordar com a pessoa e o número do sujeito: «nós chegamos». Nas outras frases, o verbo está em pessoa ou número diferentes do sujeito." },
    { t:"apl", q:"Ana escreve a legenda da foto no mural: «A turma do 7º ano ______ animada na gincana.» A forma verbal que completa corretamente a frase é:", opts:["estavam","estão","estava","estiveram"], a:2, exp:"O núcleo do sujeito é «turma» (singular), então o verbo fica no singular: «estava». As outras opções estão no plural." },
    { t:"apl", q:"Complete o recado do porteiro: «______ muitas pessoas na fila do cinema.»", opts:["Haviam","Havia","Hão","Houveram"], a:1, exp:"O verbo «haver», no sentido de «existir», é impessoal: fica sempre na 3ª pessoa do singular. O correto é «havia muitas pessoas»." },
    { t:"des", q:"Complete corretamente as duas frases: «______ dois anos que não nos vemos» e «Os alunos ______ a prova ontem.»", opts:["Fazem — fez","Faz — faz","Fazem — fizeram","Faz — fizeram"], a:3, exp:"«Fazer» indicando tempo decorrido é impessoal e fica no singular («faz dois anos»). Já na segunda frase, o verbo concorda com «os alunos»: «fizeram»." }
  ] },
  "por-7": { q: [
    { t:"fix", q:"Na frase «O pássaro azul voou», a palavra «azul» é um:", opts:["substantivo","adjetivo","verbo","advérbio"], a:1, exp:"«Azul» caracteriza o substantivo «pássaro»: é adjetivo. «Voou» é o verbo." },
    { t:"apl", q:"Na frase «O guarda-chuva de Lia e de Paula ficou na escola», o verbo está no singular porque o sujeito:", opts:["é composto","é inexistente","é simples, com núcleo «guarda-chuva»","é oculto"], a:2, exp:"Cuidado com a armadilha: «de Lia e de Paula» apenas completa o nome. O núcleo do sujeito é «guarda-chuva» (singular), por isso «ficou» no singular." },
    { t:"apl", q:"Complete a legenda da foto da turma: «Eu e meus amigos ______ a feira de ciências.»", opts:["visitou","visita","visitaste","visitamos"], a:3, exp:"«Eu e meus amigos» equivale a «nós», então o verbo fica na 1ª pessoa do plural: «visitamos»." },
    { t:"des", q:"Na frase «Cansados, os corredores chegaram ao pódio», o núcleo do sujeito e a classe da palavra «cansados» são, respectivamente:", opts:["corredores — adjetivo","chegaram — verbo","pódio — substantivo","corredores — verbo"], a:0, exp:"Dois passos: o núcleo do sujeito é «corredores» (quem chegou?), e «cansados» caracteriza esse sujeito, logo é adjetivo (aqui, predicativo do sujeito)." },
    { t:"des", q:"Assinale a única frase totalmente correta quanto à concordância verbal:", opts:["Fazem três anos que estudo nesta escola.","Chegaram atrasados os alunos e a professora.","Haviam muitas crianças no pátio.","A turma estavam animada."], a:1, exp:"Em «chegaram atrasados os alunos e a professora», o verbo concorda com o sujeito composto posposto. Nas demais: o certo seria «faz três anos», «havia muitas crianças» e «a turma estava»." }
  ] },
  "por-8": { q: [
    { t:"fix", q:"Em um poema, cada linha é chamada de:", opts:["verso","estrofe","rima","capítulo"], a:0, exp:"Cada linha de um poema é um verso. O conjunto de versos forma a estrofe." },
    { t:"fix", q:"O conjunto de versos que forma um bloco dentro do poema é chamado de:", opts:["rima","refrão","estrofe","sílaba"], a:2, exp:"A estrofe é o «parágrafo» do poema: um bloco de versos. Uma quadra, por exemplo, é uma estrofe de quatro versos." },
    { t:"apl", q:"Nos versos «O gato correu pelo telhado / e caiu de quatro no quintal gramado», as palavras «telhado» e «gramado» apresentam:", opts:["sentidos opostos","trocadilho","repetição de consoantes","rima"], a:3, exp:"Há rima: as terminações «-ado» têm sons iguais no final dos dois versos. É a semelhança sonora entre palavras no fim dos versos." },
    { t:"apl", q:"Contando as sílabas poéticas até a última sílaba tônica, o verso «O vento sopra forte no sertão» tem:", opts:["6 sílabas poéticas","10 sílabas poéticas","8 sílabas poéticas","12 sílabas poéticas"], a:1, exp:"Na contagem poética, conta-se até a última sílaba forte: O-ven-to-so-pra-for-te-no-ser-tão = 10. Como «tão» é a última tônica e está no fim, o total é 10." },
    { t:"des", q:"Observe a quadra: «O passarinho do jardim / canta baixinho sob o luar / espalha música sem fim / e alegra o nosso caminhar.» As rimas dessa quadra seguem o esquema:", opts:["AABB","ABBA","ABAB","ABCA"], a:2, exp:"«Jardim» rima com «fim» (A), e «luar» rima com «caminhar» (B). As rimas se alternam verso a verso: ABAB." }
  ] },
  "por-9": { q: [
    { t:"fix", q:"Na frase «O vento cantava na janela», atribui-se uma ação humana a um ser inanimado. Essa figura de linguagem é a:", opts:["metáfora","personificação (prosopopeia)","hipérbole","eufemismo"], a:1, exp:"Dar características ou ações humanas a seres não humanos é personificação, também chamada de prosopopeia. O vento, na verdade, não canta." },
    { t:"fix", q:"A frase «Ele chorou rios de lágrimas» é um exemplo de:", opts:["comparação","eufemismo","antítese","hipérbole"], a:3, exp:"Ninguém chora rios: há um exagero intencional para reforçar a ideia, o que caracteriza a hipérbole." },
    { t:"apl", q:"Na frase da campanha de trânsito «Seu carro é uma arma», a figura de linguagem presente é a:", opts:["metáfora","comparação explícita com o conectivo «como»","personificação","antítese"], a:0, exp:"É metáfora: a comparação entre carro e arma é feita diretamente, sem conectivo. Se fosse «o carro é como uma arma», seria comparação (símile)." },
    { t:"apl", q:"Leia a placa da lanchonete: «Aqui o hambúrguer é gigante!» A figura de linguagem usada para criar esse exagero é a:", opts:["metáfora","eufemismo","hipérbole","ironia"], a:2, exp:"Chamar um hambúrguer de «gigante» exagera o tamanho para chamar atenção do cliente: hipérbole, recurso muito comum na publicidade." },
    { t:"des", q:"Na frase «A vida é uma estrada: ora sobe, ora desce», há, respectivamente:", opts:["hipérbole e personificação","comparação explícita e hipérbole","eufemismo e antítese","metáfora e antítese"], a:3, exp:"Dois passos: «a vida é uma estrada» é metáfora (comparação sem conectivo), e «sobe/desce» opõe ideias contrárias, formando uma antítese." }
  ] },
  "por-10": { q: [
    { t:"fix", q:"O poema visual é aquele em que:", opts:["as rimas são obrigatórias em todos os versos","somente as palavras importam para o sentido","a organização das palavras e das formas na página cria imagens que se somam ao sentido","há sempre muitas ilustrações coloridas"], a:2, exp:"No poema visual, o desenho que as palavras formam na página faz parte do poema: forma e conteúdo trabalham juntos. Ele nem sempre tem ilustrações." },
    { t:"fix", q:"Para entender um poema visual, o leitor deve:", opts:["observar tanto as palavras quanto o desenho que elas formam na página","ignorar a forma e ler apenas as palavras","procurar obrigatoriamente as rimas","ler o texto de trás para frente"], a:0, exp:"A leitura do poema visual exige atenção às imagens formadas pelo texto: tamanho das letras, posição e espaços em branco também comunicam." },
    { t:"apl", q:"Um poema apresenta a palavra «cachoeira» escrita na vertical, com as letras «escorrendo» de cima a baixo pela página. Essa disposição serve para:", opts:["dificultar a leitura sem nenhum motivo","imitar visualmente a queda da água, reforçando o sentido","economizar papel na impressão","esconder o tema do poema"], a:1, exp:"A forma vertical das letras reproduz o movimento da cachoeira: a imagem criada pelo texto reforça aquilo que a palavra diz." },
    { t:"apl", q:"Para criar um poema visual sobre o tema «labirinto», uma boa estratégia seria:", opts:["escrever os versos em linhas retas e bem alinhadas","usar somente letras maiúsculas","colocar rimas em todos os versos","dispor os versos formando caminhos que se entrelaçam, como em um labirinto"], a:3, exp:"No poema visual, a forma imita o tema: versos que se cruzam e se perdem na página fazem o leitor «ver» o labirinto antes mesmo de ler." },
    { t:"des", q:"Em um poema, a palavra «silêncio» aparece sozinha, em letras pequenas, no centro de uma página toda branca. Esse recurso visual:", opts:["reforça a ideia de vazio e quietude, mostrando que os espaços em branco também comunicam","indica que o poema ficou incompleto por engano","é apenas uma economia de tinta na impressão","mostra que o tema do poema é a tipografia"], a:0, exp:"É preciso relacionar forma e sentido: a página vazia e a palavra pequena criam a sensação de silêncio. No poema visual, até o espaço em branco é linguagem." }
  ] },
  "por-11": { q: [
    { t:"fix", q:"Qual alternativa apresenta somente elementos típicos de um poema?", opts:["capítulos, personagens e enredo","tabela, legenda e fonte","parágrafos, margens e sumário","versos, estrofes e rimas"], a:3, exp:"O poema é construído com versos (linhas), estrofes (blocos) e pode ter rimas e ritmo. Capítulos e parágrafos são da prosa." },
    { t:"apl", q:"No verso «O sabiá chorava a sua tristeza», a figura de linguagem presente é a:", opts:["hipérbole","personificação","eufemismo","antítese"], a:1, exp:"«Chorar» e sentir «tristeza» são ações humanas atribuídas ao pássaro: personificação (prosopopeia)." },
    { t:"apl", q:"Complete o verso com a palavra que mantém a rima: «O menino jogava bola no chão / e ria de ______.»", opts:["montão","alegria","sorriso","contente"], a:0, exp:"«Montão» rima com «chão» (mesma terminação sonora «-ão»). As outras palavras não têm semelhança sonora com o final do primeiro verso." },
    { t:"des", q:"Leia os versos: «Meu coração é um tambor / que bate sem parar.» Nesses versos, a figura de linguagem e o elemento sonoro que une os versos são, respectivamente:", opts:["hipérbole e o número de capítulos","personificação e a pontuação","metáfora e a rima entre «tambor» e «parar»","antítese e os parágrafos"], a:2, exp:"«Coração é um tambor» é metáfora (comparação sem conectivo), e «tambor/parar» criam a rima que liga os dois versos. É preciso identificar os dois recursos." },
    { t:"des", q:"Um poema visual apresenta a palavra «foguete» escrita de baixo para cima, com letras cada vez maiores, e o último verso, «rumo às estrelas», disposto em volta de uma estrela desenhada. Esse poema combina:", opts:["apenas rima e métrica rigorosa","a direção das letras, o tamanho crescente e o desenho para construir o sentido de subida","capítulos e parágrafos numerados","sinais de pontuação e notas de rodapé"], a:1, exp:"O poeta usa três recursos visuais ao mesmo tempo — direção, tamanho e desenho — para que a página «mostre» a subida do foguete. Ler poema visual é interpretar texto e imagem juntos." }
  ] }
});
